// Ayrton Silva — weeks 5 to 8.
//
// Themes: 5 · what it actually costs   6 · energy and value
//         7 · the rental shortage      8 · location risk
//
// All figures from property-analyses/, verified 05/08/2026. Two are disputed or
// stale by design and are shown as such — that is the point of those posts:
//   · Bëllegen Akt: €40,000 confirmed by law, €45,000 announced but not
//     consolidated. Both stated, neither presented as settled.
//   · Esch unemployment 8.9 % dates from May 2024 and is labelled stale.
//
// TRADE POSTS: text-and-data, not screen captures. Switch `layout` to 'system'
// and add `media:` once real recordings exist.

export const WEEKS_5_8 = [
  // ══ WEEK 5 · WHAT IT ACTUALLY COSTS ═══════════════════════════════════
  {
    id: 'w5-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 5 · Le chiffre',
      rubric: 'Fiscalité · Bëllegen Akt',
      head: ['40 000 € par acquéreur.', 'Ou 45 000 €. Personne', 'ne le sait <em>encore</em>.'],
      standfirst: 'Le crédit d’impôt qui efface les droits d’enregistrement en résidence principale existe à deux montants différents selon la source qu’on consulte.',
      figure: '40 000 €', unit: '/ acquéreur',
      note: 'C’est le montant confirmé par la loi du 3 juillet 2025. Un communiqué gouvernemental du 16 juillet 2026 annonce 45 000 €, mais le texte consolidé n’était pas publié. Je le traite comme non vérifié.',
      rows: [
        ['Confirmé par la loi du 03/07/2025', '40 000 €'],
        ['Annoncé le 16/07/2026, non consolidé', '45 000 €'],
        ['Sur un bien à 545 000 €, droits dus', '38 150 €'],
        ['Couverts par un seul acquéreur', 'oui, dans les deux cas', true],
      ],
      source: 'pfi.public.lu — crédit d’impôt Bëllegen Akt · loi du 03/07/2025',
    },
    en: {
      kicker: 'Week 5 · The number',
      rubric: 'Tax · Bëllegen Akt',
      head: ['€40,000 per buyer.', 'Or €45,000. Nobody', 'knows <em>yet</em>.'],
      standfirst: 'The tax credit that wipes out registration duty for owner-occupiers exists at two different amounts depending which source you read.',
      figure: '€40,000', unit: '/ buyer',
      note: 'That is the amount confirmed by the law of 3 July 2025. A government release of 16 July 2026 announces €45,000, but the consolidated text was not published. I treat it as unverified.',
      rows: [
        ['Confirmed by the law of 03/07/2025', '€40,000'],
        ['Announced 16/07/2026, not consolidated', '€45,000'],
        ['On a €545,000 property, duty owed', '€38,150'],
        ['Covered by a single buyer', 'yes, under either figure', true],
      ],
      source: 'pfi.public.lu — Bëllegen Akt tax credit · law of 03/07/2025',
    },
  },
  {
    id: 'w5-tue', layout: 'system', track: 'trade',
    media: 'media/lumina-graph.png',
    fr: {
      kicker: 'Semaine 5 · Le système',
      rubric: 'Graphe · Ce qui relie tout',
      head: ['209 nœuds. 414 liens.', 'Une seule <em>mémoire</em>.'],
      standfirst: 'Chaque analyse, chaque note de marché et chaque bout de code finit relié aux autres. C’est ce qui empêche de refaire deux fois le même travail.',
      rows: [
        ['Nœuds', '209'],
        ['Liens', '414'],
        ['Sources vivantes', '4'],
        ['Ce que ça évite', 'réécrire une analyse déjà faite', true],
      ],
      screenCap: 'Capture réelle du graphe. Aucune donnée client : uniquement des notes, des analyses et de la documentation.',
      source: 'Système interne — graphe de connaissance, 4 sources',
    },
    en: {
      kicker: 'Week 5 · The system',
      rubric: 'Graph · What ties it together',
      head: ['209 nodes. 414 links.', 'One <em>memory</em>.'],
      standfirst: 'Every analysis, market note and piece of code ends up connected to the others. That is what stops the same work being done twice.',
      rows: [
        ['Nodes', '209'],
        ['Links', '414'],
        ['Live sources', '4'],
        ['What it prevents', 'rewriting an analysis that exists', true],
      ],
      screenCap: 'Real capture of the graph. No client data: notes, analyses and documentation only.',
      source: 'Internal system — knowledge graph, 4 sources',
    },
  },
  {
    id: 'w5-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 5 · Comment je vérifie',
      rubric: 'Méthode · Cash à la signature',
      head: ['Comment je calcule le', 'cash qu’il faut vraiment', 'sortir le <em>jour J</em>.'],
      standfirst: 'La contrainte bloquante au Luxembourg n’est presque jamais l’apport. Ce sont les frais, et ils changent du tout au tout selon l’usage.',
      steps: [
        ['01', 'Établir l’usage avant tout chiffre', 'Résidence principale ou locatif. Cette seule réponse fait varier le cash nécessaire d’un facteur trente sur un même bien.'],
        ['02', 'Poser les droits à 7 %', 'Six pour cent d’enregistrement, un de transcription. Sur 545 000 €, cela fait 38 150 € dus avant toute réduction.'],
        ['03', 'Appliquer le Bëllegen Akt, s’il s’applique', 'Résidence principale uniquement, occupation effective dans les deux ans, sinon récupération avec intérêts. En locatif, il ne s’applique pas du tout.'],
        ['04', 'Ajouter le notaire, puis l’apport', 'Environ 1 % plus débours. L’apport ne vient qu’à la fin, et c’est rarement lui qui bloque le dossier.'],
      ],
      statement: 'Un acheteur qui découvre les 38 150 € trois semaines avant l’acte n’a pas un problème de financement. Il a un problème de conseil.',
      source: 'pfi.public.lu · loi du 03/07/2025 · barème notarial',
    },
    en: {
      kicker: 'Week 5 · How I check',
      rubric: 'Method · Cash at signing',
      head: ['How I work out the cash', 'you actually need on', 'the <em>day</em>.'],
      standfirst: 'The binding constraint in Luxembourg is almost never the deposit. It is the fees, and they change completely depending on use.',
      steps: [
        ['01', 'Establish the use before any figure', 'Primary residence or buy-to-let. That single answer moves the cash required by a factor of thirty on the same property.'],
        ['02', 'Put duty at 7 %', 'Six per cent registration, one transcription. On €545,000 that is €38,150 owed before any relief.'],
        ['03', 'Apply the Bëllegen Akt, if it applies', 'Primary residence only, effective occupation within two years, otherwise recovered with interest. On a rental it does not apply at all.'],
        ['04', 'Add the notary, then the deposit', 'Roughly 1 % plus disbursements. The deposit comes last, and it is rarely what blocks the file.'],
      ],
      statement: 'A buyer who discovers the €38,150 three weeks before the deed does not have a financing problem. They have an advice problem.',
      source: 'pfi.public.lu · law of 03/07/2025 · notarial scale',
    },
  },
  {
    id: 'w5-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 5 · Lecture de marché',
      rubric: 'Fiscalité · Détention et sortie',
      head: ['L’impôt foncier ici n’a rien', 'à voir avec ce que vous', 'avez <em>lu ailleurs</em>.'],
      standfirst: 'Deux hypothèses importées faussent régulièrement les projections des acheteurs étrangers. Les deux sont fausses au Luxembourg.',
      rows: [
        ['Impôt foncier annuel', 'souvent quelques centaines d’euros'],
        ['Hypothèse américaine courante', '1 à 2 % de la valeur — fausse ici', true],
        ['Plus-value, résidence principale', 'exonérée'],
        ['Taux réduit à 10,5 %, seuil 2 ans', 'en vigueur du 01/01/2024 au 30/06/2025 seulement'],
        ['Régime actuel', 'à reconfirmer — non vérifié', true],
      ],
      statement: 'Le régime de plus-value a bougé deux fois en dix-huit mois. Toute projection de sortie doit être confirmée auprès du notaire, pas reprise d’un article.',
      source: 'impotsdirects.public.lu · pfi.public.lu — statut à reconfirmer',
    },
    en: {
      kicker: 'Week 5 · Market read',
      rubric: 'Tax · Holding and exit',
      head: ['Property tax here has', 'nothing to do with what', 'you read <em>elsewhere</em>.'],
      standfirst: 'Two imported assumptions regularly distort foreign buyers’ projections. Both are wrong in Luxembourg.',
      rows: [
        ['Annual property tax', 'often a few hundred euros'],
        ['Common American assumption', '1–2 % of value — wrong here', true],
        ['Capital gain, primary residence', 'exempt'],
        ['Reduced 10.5 % rate, 2-year threshold', 'in force only 01/01/2024 to 30/06/2025'],
        ['Current regime', 'to be reconfirmed — unverified', true],
      ],
      statement: 'The capital gains regime has moved twice in eighteen months. Any exit projection must be confirmed with the notary, not lifted from an article.',
      source: 'impotsdirects.public.lu · pfi.public.lu — status to reconfirm',
    },
  },
  {
    id: 'w5-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 5 · Note de build',
      rubric: 'Ce que j’ai ajouté cette semaine',
      head: ['Un chiffre contesté', 'sort avec ses <em>deux</em>', 'valeurs.'],
      standfirst: 'Le Bëllegen Akt m’a forcé à trancher une question de conception : que fait le système quand deux sources officielles se contredisent ?',
      statement: 'Il ne choisit pas. Il affiche les deux, cite chaque source, et marque laquelle est consolidée. Choisir à la place du notaire serait plus élégant et parfaitement irresponsable.',
      rows: [
        ['Source A — loi du 03/07/2025', '40 000 €, consolidée'],
        ['Source B — communiqué 16/07/2026', '45 000 €, non consolidée'],
        ['Ce que fait le système', 'affiche les deux'],
        ['Ce qu’il ne fait pas', 'trancher à votre place', true],
      ],
      source: 'pfi.public.lu · gouvernement.lu',
    },
    en: {
      kicker: 'Week 5 · Build note',
      rubric: 'What I added this week',
      head: ['A disputed number ships', 'with <em>both</em> values.'],
      standfirst: 'The Bëllegen Akt forced a design decision: what should the system do when two official sources contradict each other?',
      statement: 'It does not choose. It shows both, cites each source, and marks which one is consolidated. Choosing on the notary’s behalf would be more elegant and completely irresponsible.',
      rows: [
        ['Source A — law of 03/07/2025', '€40,000, consolidated'],
        ['Source B — release of 16/07/2026', '€45,000, not consolidated'],
        ['What the system does', 'shows both'],
        ['What it does not do', 'decide for you', true],
      ],
      source: 'pfi.public.lu · gouvernement.lu',
    },
  },

  // ══ WEEK 6 · ENERGY AND VALUE ═════════════════════════════════════════
  {
    id: 'w6-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 6 · Le chiffre',
      rubric: 'Énergie · Prime de classe',
      head: ['La classe énergétique vaut', 'plus que l’<em>étage</em>.'],
      standfirst: 'Sur les comparables relevés à Esch, l’écart entre l’ancien non rénové et le rénové ou neuf est le facteur de prix le plus net que j’aie mesuré.',
      figure: '+38 %', unit: 'au m²',
      note: 'Échantillon restreint : à traiter comme un ordre de grandeur, pas comme une élasticité. Mais la direction est nette et elle se retrouve sur chaque dossier.',
      rows: [
        ['CPE E/F — ancien non rénové', '5 073 €/m²'],
        ['CPE D ou VEFA neuf', '6 999 €/m²'],
        ['Écart mesuré', '≈ +38 %', true],
        ['Fiabilité', 'ordre de grandeur, échantillon limité'],
      ],
      source: 'Comparables relevés sur athome.lu et immotop.lu, Esch-sur-Alzette (août 2026)',
    },
    en: {
      kicker: 'Week 6 · The number',
      rubric: 'Energy · The class premium',
      head: ['Energy class is worth more', 'than the <em>floor</em> you’re on.'],
      standfirst: 'Across the comparables I captured in Esch, the gap between unrenovated older stock and renovated or new build is the sharpest price factor I have measured.',
      figure: '+38 %', unit: 'per m²',
      note: 'Small sample: treat it as an order of magnitude, not an elasticity. But the direction is clear and it shows up on every file.',
      rows: [
        ['CPE E/F — unrenovated older stock', '€5,073/m²'],
        ['CPE D or new off-plan', '€6,999/m²'],
        ['Measured gap', '≈ +38 %', true],
        ['Reliability', 'order of magnitude, limited sample'],
      ],
      source: 'Comparables captured on athome.lu and immotop.lu, Esch-sur-Alzette (August 2026)',
    },
  },
  {
    id: 'w6-tue', layout: 'read', track: 'trade',
    fr: {
      kicker: 'Semaine 6 · Le système',
      rubric: 'Module · Lecture du CPE',
      head: ['Le système ne croit pas', 'un CPE <em>provisoire</em>.'],
      standfirst: 'La classe énergétique est le premier facteur de prix, ce qui en fait aussi le premier endroit où une analyse peut se tromper de bonne foi.',
      rows: [
        ['CPE annoncé dans l’annonce', 'obligatoire, mais parfois provisoire'],
        ['Traitement d’un CPE provisoire', 'marqué, prime non validée'],
        ['Effet sur la fourchette', 'élargie tant que le passeport manque'],
        ['Ce qui lève le doute', 'le passeport définitif, rien d’autre', true],
      ],
      statement: 'Sur un immeuble de 1950 annoncé B/C provisoire, la prime demandée repose entièrement sur un document qui n’existe pas encore. Ça se dit avant l’offre, pas après.',
      source: 'Système interne · CPE obligatoire dans toute annonce (Luxembourg)',
    },
    en: {
      kicker: 'Week 6 · The system',
      rubric: 'Module · Reading the energy certificate',
      head: ['The system does not trust', 'a <em>provisional</em> certificate.'],
      standfirst: 'Energy class is the strongest price factor, which makes it the first place an analysis can be wrong in good faith.',
      rows: [
        ['Class stated in the listing', 'mandatory, but sometimes provisional'],
        ['How a provisional class is handled', 'flagged, premium not validated'],
        ['Effect on the valuation range', 'widened while the certificate is missing'],
        ['What settles it', 'the definitive certificate, nothing else', true],
      ],
      statement: 'On a 1950 building advertised as provisional B/C, the premium being asked rests entirely on a document that does not exist yet. That gets said before the offer, not after.',
      source: 'Internal system · energy certificate mandatory in every Luxembourg listing',
    },
  },
  {
    id: 'w6-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 6 · Comment je vérifie',
      rubric: 'Méthode · Rénovation déjà payée',
      head: ['Comment je vérifie si la', 'rénovation a déjà été', '<em>payée</em> — par vous.'],
      standfirst: 'Acheter un bien déjà rénové paraît plus simple. Fiscalement, c’est surtout plus cher, et le vendeur a encaissé l’avantage.',
      steps: [
        ['01', 'Identifier qui a engagé les travaux', 'La TVA logement à 3 % au lieu de 17 % et les aides Klimabonus bénéficient à celui qui commande et paie. Pas au suivant.'],
        ['02', 'Comprendre ce que vous rachetez', 'Un bien déjà rénové intègre ces avantages dans le prix demandé. Vous les payez, vous ne les récupérez pas.'],
        ['03', 'Vérifier le plafond et l’antériorité', 'L’avantage TVA est plafonné à 50 000 € par logement et suppose un accord préalable de l’AED avant travaux. Il ne s’applique jamais rétroactivement.'],
        ['04', 'Chercher ce qui reste comme levier', 'Un éventuel amortissement accéléré sur la part rénovation, et une meilleure liquidité à la revente. Mais plus aucune subvention à capter.'],
      ],
      statement: 'Un CPE déjà excellent est une bonne nouvelle pour habiter, et la fin du levier de valorisation pour investir.',
      source: 'pfi.public.lu — TVA logement 3 %, plafond 50 000 € · Klimabonus / PRIMe House',
    },
    en: {
      kicker: 'Week 6 · How I check',
      rubric: 'Method · Renovation already paid for',
      head: ['How I check whether the', 'renovation was already', 'paid for — by <em>you</em>.'],
      standfirst: 'Buying an already-renovated property looks simpler. In tax terms it is mainly more expensive, and the seller has banked the benefit.',
      steps: [
        ['01', 'Identify who commissioned the works', 'The 3 % housing VAT instead of 17 %, and the Klimabonus subsidies, go to whoever orders and pays. Not to the next owner.'],
        ['02', 'Understand what you are buying back', 'An already-renovated property has those advantages built into the asking price. You pay for them; you do not recover them.'],
        ['03', 'Check the cap and the timing', 'The VAT advantage is capped at €50,000 per dwelling and requires prior AED approval before works. It never applies retroactively.'],
        ['04', 'Find what leverage remains', 'Possible accelerated depreciation on the renovation share, and better liquidity at resale. But no subsidy left to capture.'],
      ],
      statement: 'An already-excellent energy class is good news if you are moving in, and the end of the value-add lever if you are investing.',
      source: 'pfi.public.lu — 3 % housing VAT, €50,000 cap · Klimabonus / PRIMe House',
    },
  },
  {
    id: 'w6-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 6 · Lecture de marché',
      rubric: 'Amortissement · Ce qui est déductible',
      head: ['Un immeuble de 1950', 'ne s’amortit pas comme', 'un <em>neuf</em>.'],
      standfirst: 'Le taux accéléré que citent beaucoup de simulateurs ne s’applique qu’aux constructions récentes. Sur l’ancien, c’est le taux normal.',
      rows: [
        ['Taux accéléré, 4 %', 'immeubles achevés depuis moins de 5 ans'],
        ['Taux normal applicable à l’ancien', '2 % / an', true],
        ['Base amortissable', 'prix moins ~25 % de quote-part terrain'],
        ['Sur un bien à 545 000 €', '≈ 8 175 € / an déductibles'],
        ['Part rénovation énergétique', 'taux exact non vérifié', true],
      ],
      statement: 'Une projection locative qui applique 4 % à un immeuble d’avant 1970 surestime la déduction du double. C’est une erreur fréquente, et elle est vérifiable en une ligne.',
      source: 'impotsdirects.public.lu — art. 106 LIR',
    },
    en: {
      kicker: 'Week 6 · Market read',
      rubric: 'Depreciation · What is deductible',
      head: ['A 1950 building does not', 'depreciate like a <em>new</em> one.'],
      standfirst: 'The accelerated rate quoted by many simulators applies only to recent construction. On older stock it is the standard rate.',
      rows: [
        ['Accelerated rate, 4 %', 'buildings completed within the last 5 years'],
        ['Standard rate for older stock', '2 % / year', true],
        ['Depreciable base', 'price less ~25 % land share'],
        ['On a €545,000 property', '≈ €8,175 / year deductible'],
        ['Energy renovation share', 'exact rate unverified', true],
      ],
      statement: 'A rental projection applying 4 % to a pre-1970 building overstates the deduction by double. It is a common error, and it is checkable in one line.',
      source: 'impotsdirects.public.lu — art. 106 LIR',
    },
  },
  {
    id: 'w6-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 6 · Note de build',
      rubric: 'Ce que j’ai ajouté cette semaine',
      head: ['Détecter la valorisation', 'déjà <em>captée</em>.'],
      standfirst: 'Le système signale désormais quand le levier énergétique a été consommé par le vendeur.',
      statement: 'C’est contre-intuitif à coder : un bon CPE dégrade le score d’investissement, parce qu’il ne reste plus rien à créer. Le bien est meilleur ; l’opération est moins intéressante.',
      rows: [
        ['Signal déclencheur', 'CPE B ou C sur bâti ancien'],
        ['Ce qui est vérifié', 'qui a engagé et payé les travaux'],
        ['Effet sur le score value-add', 'ramené à zéro'],
        ['Effet sur le score résidence principale', 'relevé', true],
      ],
      source: 'Règle interne · pfi.public.lu — TVA logement et aides',
    },
    en: {
      kicker: 'Week 6 · Build note',
      rubric: 'What I added this week',
      head: ['Detecting value already', '<em>captured</em>.'],
      standfirst: 'The system now flags when the energy lever has been consumed by the seller.',
      statement: 'It is counter-intuitive to code: a good energy class lowers the investment score, because there is nothing left to create. The property is better; the deal is less interesting.',
      rows: [
        ['Trigger signal', 'class B or C on older building stock'],
        ['What gets checked', 'who commissioned and paid for the works'],
        ['Effect on the value-add score', 'reduced to zero'],
        ['Effect on the primary-residence score', 'raised', true],
      ],
      source: 'Internal rule · pfi.public.lu — housing VAT and subsidies',
    },
  },

  // ══ WEEK 7 · THE RENTAL SHORTAGE ══════════════════════════════════════
  {
    id: 'w7-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 7 · Le chiffre',
      rubric: 'Offre et demande · Esch-sur-Alzette',
      head: ['792 biens à vendre.', '45 à <em>louer</em>.'],
      standfirst: 'Dans une commune de près de 38 000 habitants. Ce n’est pas un accident de marché, c’est une conséquence directe de la loi.',
      figure: '17,6', unit: ': 1',
      note: 'Le plafond légal de loyer comprime le rendement au point que les propriétaires préfèrent vendre plutôt que louer. La pénurie locative est un effet réglementaire, pas démographique.',
      rows: [
        ['Biens à la vente', '792'],
        ['Biens à la location', '45', true],
        ['Population communale', '37 922'],
        ['Ce que ça crée', 'marché acheteur / marché bailleur'],
      ],
      source: 'immotop.lu (juillet 2026) · loi du 21/09/2006 · STATEC',
    },
    en: {
      kicker: 'Week 7 · The number',
      rubric: 'Supply and demand · Esch-sur-Alzette',
      head: ['792 properties for sale.', '45 to <em>rent</em>.'],
      standfirst: 'In a commune of nearly 38,000 people. This is not a market accident, it is a direct consequence of the law.',
      figure: '17.6', unit: ': 1',
      note: 'The statutory rent cap compresses yield to the point where owners prefer to sell rather than let. The rental shortage is a regulatory effect, not a demographic one.',
      rows: [
        ['Properties for sale', '792'],
        ['Properties to rent', '45', true],
        ['Commune population', '37,922'],
        ['What it creates', 'buyer’s market / landlord’s market'],
      ],
      source: 'immotop.lu (July 2026) · law of 21/09/2006 · STATEC',
    },
  },
  {
    id: 'w7-tue', layout: 'read', track: 'trade',
    fr: {
      kicker: 'Semaine 7 · Le système',
      rubric: 'Indicateur · Ratio vente / location',
      head: ['Le seul indicateur de', 'tension que je peux', 'vraiment <em>calculer</em>.'],
      standfirst: 'Sans registre de transactions, les mois de stock et le taux d’absorption sont hors de portée. Le ratio vente / location, lui, se compte.',
      rows: [
        ['Esch-sur-Alzette', '792 / 45 — 17,6 : 1'],
        ['Niederkorn', '91 / 3 — 30 : 1', true],
        ['Ce qu’il mesure', 'l’arbitrage vendre-ou-louer des propriétaires'],
        ['Ce qu’il ne mesure pas', 'la vitesse d’écoulement — non calculable'],
      ],
      statement: 'C’est un indicateur pauvre comparé à ce qu’on aurait avec un MLS. Mais il est réel, il est reproductible, et il ne demande d’inventer aucune donnée.',
      source: 'immotop.lu (juin–juillet 2026)',
    },
    en: {
      kicker: 'Week 7 · The system',
      rubric: 'Indicator · Sale-to-rent ratio',
      head: ['The only tension metric', 'I can actually', '<em>compute</em>.'],
      standfirst: 'Without a transaction register, months of inventory and absorption rate are out of reach. The sale-to-rent ratio can be counted.',
      rows: [
        ['Esch-sur-Alzette', '792 / 45 — 17.6 : 1'],
        ['Niederkorn', '91 / 3 — 30 : 1', true],
        ['What it measures', 'owners’ sell-or-let decision'],
        ['What it does not measure', 'clearance speed — not calculable'],
      ],
      statement: 'It is a poor indicator compared with what an MLS would give. But it is real, it is reproducible, and it requires inventing nothing.',
      source: 'immotop.lu (June–July 2026)',
    },
  },
  {
    id: 'w7-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 7 · Comment je vérifie',
      rubric: 'Méthode · Lire un déséquilibre',
      head: ['Comment je lis un marché', 'où acheteurs et locataires', 'vivent l’<em>inverse</em>.'],
      standfirst: 'La même commune peut être confortable pour un acheteur et brutale pour un locataire. Ce sont deux marchés, pas deux humeurs.',
      steps: [
        ['01', 'Compter les deux stocks séparément', 'Sept cent quatre-vingt-douze contre quarante-cinq. Le déséquilibre saute aux yeux dès qu’on arrête de parler du « marché » au singulier.'],
        ['02', 'Chercher la cause réglementaire avant la cause économique', 'Le plafond des 5 % rend la mise en location peu rentable. Les propriétaires arbitrent, et ils vendent.'],
        ['03', 'En tirer la conséquence pour chaque côté', 'À l’achat, stock élevé et prix en repli donnent une vraie marge de négociation. À la location, quarante-cinq biens et des loyers au plus haut ne laissent rien.'],
        ['04', 'Refuser d’estimer ce qui n’est pas publié', 'Mois de stock et délai d’écoulement n’existent pas ici. Les inventer donnerait une fausse précision à une lecture par ailleurs correcte.'],
      ],
      statement: 'Un marché acheteur et une pénurie locative peuvent coexister dans la même rue. Ce n’est pas une contradiction, c’est une conséquence de la loi.',
      source: 'immotop.lu (juillet 2026) · loi du 21/09/2006',
    },
    en: {
      kicker: 'Week 7 · How I check',
      rubric: 'Method · Reading an imbalance',
      head: ['How I read a market where', 'buyers and renters live', 'the <em>opposite</em> reality.'],
      standfirst: 'The same commune can be comfortable for a buyer and brutal for a tenant. Those are two markets, not two moods.',
      steps: [
        ['01', 'Count the two stocks separately', 'Seven hundred and ninety-two against forty-five. The imbalance is obvious the moment you stop saying "the market" in the singular.'],
        ['02', 'Look for the regulatory cause before the economic one', 'The 5 % cap makes letting unattractive. Owners weigh it up, and they sell.'],
        ['03', 'Draw the consequence for each side', 'On the buy side, high stock and softening prices give real negotiating room. On the rental side, forty-five properties and record rents leave none.'],
        ['04', 'Refuse to estimate what is not published', 'Months of inventory and clearance time do not exist here. Inventing them would give false precision to an otherwise sound reading.'],
      ],
      statement: 'A buyer’s market and a rental shortage can coexist on the same street. That is not a contradiction, it is a consequence of the law.',
      source: 'immotop.lu (July 2026) · law of 21/09/2006',
    },
  },
  {
    id: 'w7-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 7 · Lecture de marché',
      rubric: 'Niederkorn · Le cas extrême',
      head: ['Trente biens à vendre', 'pour un seul à <em>louer</em>.'],
      standfirst: 'À Niederkorn, le même mécanisme produit un déséquilibre presque deux fois plus marqué qu’à Esch, avec des loyers qui montent d’autant plus vite.',
      rows: [
        ['Ratio vente / location', '30 : 1', true],
        ['Loyer annoncé, sur 1 an', '+7,53 %'],
        ['Loyer sur 5 ans', '+46,3 %', true],
        ['Prix de vente, sur 3 ans', '−10,4 %'],
        ['Creux local atteint', 'avril 2026'],
      ],
      statement: 'Prix en baisse de 10 % sur trois ans, loyers en hausse de 46 % sur cinq. Ce ne sont pas deux tendances contradictoires : c’est la même cause vue des deux côtés.',
      source: 'immotop.lu, Niederkorn (juin 2026)',
    },
    en: {
      kicker: 'Week 7 · Market read',
      rubric: 'Niederkorn · The extreme case',
      head: ['Thirty properties for sale', 'to every one to <em>rent</em>.'],
      standfirst: 'In Niederkorn the same mechanism produces an imbalance nearly twice as sharp as Esch, with rents climbing correspondingly faster.',
      rows: [
        ['Sale-to-rent ratio', '30 : 1', true],
        ['Advertised rent, 1 year', '+7.53 %'],
        ['Rent over 5 years', '+46.3 %', true],
        ['Sale price, over 3 years', '−10.4 %'],
        ['Local trough reached', 'April 2026'],
      ],
      statement: 'Prices down 10 % over three years, rents up 46 % over five. Those are not two contradictory trends: it is one cause seen from both sides.',
      source: 'immotop.lu, Niederkorn (June 2026)',
    },
  },
  {
    id: 'w7-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 7 · Note de build',
      rubric: 'Ce que j’ai appris cette semaine',
      head: ['La pénurie locative est', 'un artefact <em>juridique</em>.'],
      standfirst: 'En modélisant le ratio sur plusieurs localités, une chose est devenue difficile à ignorer.',
      statement: 'Le déséquilibre ne suit pas la démographie. Il suit le rendement autorisé. Là où le plafond mord le plus fort, le ratio explose — et c’est reproductible d’une commune à l’autre.',
      rows: [
        ['Ce que je pensais mesurer', 'la tension démographique'],
        ['Ce que je mesure en réalité', 'l’arbitrage économique des propriétaires', true],
        ['Implication pour un bailleur', 'la rareté ne compense pas le plafond'],
        ['Implication pour un acheteur', 'le stock à vendre est structurel, pas conjoncturel'],
      ],
      source: 'immotop.lu · loi du 21/09/2006 · projet de loi n°8184',
    },
    en: {
      kicker: 'Week 7 · Build note',
      rubric: 'What I learned this week',
      head: ['The rental shortage is a', '<em>legal</em> artefact.'],
      standfirst: 'Modelling the ratio across several localities made one thing hard to ignore.',
      statement: 'The imbalance does not track demographics. It tracks permitted yield. Where the cap bites hardest, the ratio explodes — and it reproduces from one commune to the next.',
      rows: [
        ['What I thought I was measuring', 'demographic pressure'],
        ['What I am actually measuring', 'owners’ economic arbitrage', true],
        ['Implication for a landlord', 'scarcity does not offset the cap'],
        ['Implication for a buyer', 'the for-sale stock is structural, not cyclical'],
      ],
      source: 'immotop.lu · law of 21/09/2006 · draft law no. 8184',
    },
  },

  // ══ WEEK 8 · LOCATION RISK ════════════════════════════════════════════
  {
    id: 'w8-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 8 · Le chiffre',
      rubric: 'Due diligence · Ce qu’on ne peut pas savoir',
      head: ['Aucun indice de criminalité', 'par quartier n’est', '<em>publié</em> ici.'],
      standfirst: 'La Police Grand-Ducale ne diffuse que des statistiques nationales et régionales. Toute carte de « sécurité par quartier » au Luxembourg est une fabrication.',
      figure: '0', unit: 'donnée par quartier',
      note: 'Je préfère le dire que le contourner. Un acheteur qui me demande si un quartier est sûr mérite « ce n’est pas publié, allez-y le soir » plutôt qu’une invention rassurante.',
      rows: [
        ['Statistiques nationales', 'publiées'],
        ['Statistiques régionales', 'publiées'],
        ['Ventilation par quartier', 'non publiée', true],
        ['Ce que je recommande', 'la visite à des heures différentes'],
      ],
      source: 'Police Grand-Ducale — diffusion nationale et régionale uniquement',
    },
    en: {
      kicker: 'Week 8 · The number',
      rubric: 'Due diligence · What cannot be known',
      head: ['No crime index by', 'neighbourhood is', '<em>published</em> here.'],
      standfirst: 'The Police Grand-Ducale releases national and regional statistics only. Any "neighbourhood safety" map of Luxembourg is a fabrication.',
      figure: '0', unit: 'neighbourhood data',
      note: 'I would rather say so than work around it. A buyer who asks whether an area is safe deserves "it is not published, go and stand there in the evening" rather than a reassuring invention.',
      rows: [
        ['National statistics', 'published'],
        ['Regional statistics', 'published'],
        ['Breakdown by neighbourhood', 'not published', true],
        ['What I recommend instead', 'visiting at different hours'],
      ],
      source: 'Police Grand-Ducale — national and regional release only',
    },
  },
  {
    id: 'w8-tue', layout: 'system', track: 'trade',
    media: 'media/lumina-intel.png',
    fr: {
      kicker: 'Semaine 8 · Le système',
      rubric: 'Veille · Ce que le module refuse',
      head: ['Le module de veille', 'affiche ce qu’il ne', '<em>fait pas</em>.'],
      standfirst: 'Sur un marché où la donnée est rare, la tentation de la collecter n’importe comment est réelle. Cette page existe pour fermer la question.',
      rows: [
        ['Scraping d’URL', 'non'],
        ['Collecte de contacts personnels', 'non'],
        ['Création de profils', 'non'],
        ['Envoi de messages', 'non', true],
        ['Sources', 'API autorisées, base d’accès conservée'],
      ],
      screenCap: 'Capture réelle. Chaque source garde la preuve de sa base d’accès et la date de connexion.',
      source: 'Système interne — module Public Intelligence',
    },
    en: {
      kicker: 'Week 8 · The system',
      rubric: 'Research · What the module refuses',
      head: ['The research module', 'displays what it does', '<em>not</em> do.'],
      standfirst: 'In a market where data is scarce, the temptation to collect it any way you can is real. This page exists to close the question.',
      rows: [
        ['URL scraping', 'no'],
        ['Personal contact collection', 'no'],
        ['Profile building', 'no'],
        ['Sending messages', 'no', true],
        ['Sources', 'permitted APIs, access basis retained'],
      ],
      screenCap: 'Real capture. Every source keeps evidence of its access basis and the date it was connected.',
      source: 'Internal system — Public Intelligence module',
    },
  },
  {
    id: 'w8-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 8 · Comment je vérifie',
      rubric: 'Méthode · Avant toute offre',
      head: ['Les quatre vérifications', 'que je fais avant', 'toute <em>offre</em>.'],
      standfirst: 'Aucune n’est spectaculaire. Ensemble, elles évitent la quasi-totalité des mauvaises surprises que j’ai vues arriver après signature.',
      steps: [
        ['01', 'Le passeport énergétique définitif', 'Pas le provisoire. La prime de prix repose dessus, et un classement dégradé change le positionnement du bien.'],
        ['02', 'Le budget du syndic et le fonds de réserve', 'Une copropriété de cinq lots répartit une toiture sur cinq quotes-parts au lieu de trente. La gouvernance est simple, la facture ne l’est pas.'],
        ['03', 'Le zonage de la parcelle', 'PAG, PAP, zones inondables, et le CASIPO dans le Sud. Quinze minutes sur geoportail.lu avant de s’engager sur trente ans.'],
        ['04', 'Les montants fiscaux auprès du notaire', 'Bëllegen Akt, régime de plus-value, plafonds de déduction. Trois chiffres qui ont bougé récemment et qu’aucune simulation ne remplace.'],
      ],
      statement: 'Ce ne sont pas des précautions d’investisseur. C’est le minimum pour un achat de résidence principale, et presque personne ne les fait toutes.',
      source: 'geoportail.lu · emwelt.lu · pfi.public.lu · impotsdirects.public.lu',
    },
    en: {
      kicker: 'Week 8 · How I check',
      rubric: 'Method · Before any offer',
      head: ['The four checks I run', 'before any <em>offer</em>.'],
      standfirst: 'None is spectacular. Together they prevent almost every unpleasant surprise I have seen land after signature.',
      steps: [
        ['01', 'The definitive energy certificate', 'Not the provisional one. The price premium rests on it, and a downgrade changes the property’s positioning.'],
        ['02', 'The managing agent’s budget and reserve fund', 'A five-unit co-ownership splits a roof across five shares instead of thirty. The governance is simple; the invoice is not.'],
        ['03', 'The parcel’s zoning', 'PAG, PAP, flood zones, and CASIPO in the south. Fifteen minutes on geoportail.lu before committing for thirty years.'],
        ['04', 'The tax amounts, with the notary', 'Bëllegen Akt, capital gains regime, deduction caps. Three figures that have moved recently and that no simulation replaces.'],
      ],
      statement: 'These are not investor precautions. They are the minimum for buying a home, and almost nobody does all four.',
      source: 'geoportail.lu · emwelt.lu · pfi.public.lu · impotsdirects.public.lu',
    },
  },
  {
    id: 'w8-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 8 · Lecture de marché',
      rubric: 'Belval · Fin d’un cycle',
      head: ['Le moteur du Sud a déjà', 'produit l’essentiel de', 'son <em>effet</em>.'],
      standfirst: 'Acheter à Esch aujourd’hui en pariant que Belval va tout tirer vers le haut, c’est arriver quinze ans après le début de l’histoire.',
      rows: [
        ['Investissement cumulé', '3,2 milliards d’euros'],
        ['Masterplan restant à développer', 'moins de 15 %', true],
        ['Engagé en infrastructure 2025-2026', '180 millions d’euros'],
        ['Prix à Belval-Université', '4 911 €/m², stable à −0,0 %'],
        ['Loyer à Belval-Université', '15,75 €/m² — faible', true],
      ],
      statement: 'Le quartier qui porte tout le récit du Sud se vend sous la moyenne communale et se loue mal. L’offre neuve y a rattrapé la demande.',
      source: 'Fonds Belval · Paperjam · immotop.lu (juillet 2026)',
    },
    en: {
      kicker: 'Week 8 · Market read',
      rubric: 'Belval · The end of a cycle',
      head: ['The South’s engine has', 'already delivered most', 'of its <em>effect</em>.'],
      standfirst: 'Buying in Esch today on the bet that Belval will lift everything is arriving fifteen years into the story.',
      rows: [
        ['Cumulative investment', '€3.2 billion'],
        ['Masterplan left to develop', 'less than 15 %', true],
        ['Committed to infrastructure 2025-2026', '€180 million'],
        ['Price at Belval-Université', '€4,911/m², flat at −0.0 %'],
        ['Rent at Belval-Université', '€15.75/m² — weak', true],
      ],
      statement: 'The district carrying the whole southern narrative sells below the commune average and rents poorly. New supply has caught up with demand there.',
      source: 'Fonds Belval · Paperjam · immotop.lu (July 2026)',
    },
  },
  {
    id: 'w8-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 8 · Note de build',
      rubric: 'La sortie la plus utile',
      head: ['Chaque analyse se termine', 'par ce qu’elle ne <em>sait</em>', 'pas encore.'],
      standfirst: 'Après huit semaines à publier des chiffres, la partie du système que j’utilise le plus n’est pas le score.',
      statement: 'C’est la liste des vérifications restantes. Un score dit où vous en êtes ; la liste dit quoi faire demain matin. Sur un marché sans registre, la seconde vaut plus que le premier.',
      rows: [
        ['Vérifications sur le bien', 'CPE définitif, syndic, zonage, travaux'],
        ['Vérifications fiscales', 'Bëllegen Akt, plus-value, déductions'],
        ['Vérifications financières', 'taux personnalisé, impôt foncier communal'],
        ['Chaque ligne porte', 'sa source et son statut', true],
      ],
      source: 'Système interne — sortie standard de toute analyse',
    },
    en: {
      kicker: 'Week 8 · Build note',
      rubric: 'The most useful output',
      head: ['Every analysis ends with', 'what it does not <em>know</em>', 'yet.'],
      standfirst: 'After eight weeks of publishing figures, the part of the system I use most is not the score.',
      statement: 'It is the list of remaining checks. A score tells you where you stand; the list tells you what to do tomorrow morning. In a market with no register, the second is worth more than the first.',
      rows: [
        ['Property checks', 'definitive certificate, agent, zoning, works'],
        ['Tax checks', 'Bëllegen Akt, capital gains, deductions'],
        ['Financial checks', 'personalised rate, communal property tax'],
        ['Every line carries', 'its source and its status', true],
      ],
      source: 'Internal system — standard output of every analysis',
    },
  },
];
