// Ayrton Silva — weeks 2 to 4. Appended to POSTS by data.js.
//
// TRADE POSTS: built as text-and-data rather than screen captures, because no
// real recordings of LUMINA exist yet. Each Tuesday post is written so a screen
// capture drops straight in — change `layout` to 'system' and add
// `media: 'media/xxx.jpg'`. Nothing here fakes a screenshot.

export const WEEKS_2_4 = [
  // ══ WEEK 2 ════════════════════════════════════════════════════════════
  {
    id: 'w2-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 2 · Le chiffre',
      rubric: 'Coût réel · Acquisition',
      head: ['Un bien à 545 000 €', 'vous coûte <em>588 600 €</em>.'],
      standfirst: 'Les frais d’acquisition ne sont pas une ligne annexe. Ils sont la base de tout calcul de rendement sérieux.',
      figure: '43 600 €', unit: '',
      note: 'C’est ce capital investi qui doit servir de référence, jamais le prix affiché. C’est l’erreur la plus fréquente que je vois dans les dossiers, y compris professionnels.',
      rows: [
        ['Droits d’enregistrement (6 %)', '32 700 €'],
        ['Droit de transcription (1 %)', '5 450 €'],
        ['Notaire (~1 %)', '5 450 €'],
        ['Capital réellement investi', '588 600 €', true],
      ],
      source: 'pfi.public.lu — droits d’enregistrement et de transcription',
    },
    en: {
      kicker: 'Week 2 · The number',
      rubric: 'Real cost · Acquisition',
      head: ['A €545,000 property', 'costs you <em>€588,600</em>.'],
      standfirst: 'Acquisition costs are not a footnote. They are the basis of any serious yield calculation.',
      figure: '€43,600', unit: '',
      note: 'That invested capital is the reference, never the asking price. It is the most common error I see in investment files, including professional ones.',
      rows: [
        ['Registration duty (6 %)', '€32,700'],
        ['Transcription duty (1 %)', '€5,450'],
        ['Notary (~1 %)', '€5,450'],
        ['Capital actually invested', '€588,600', true],
      ],
      source: 'pfi.public.lu — registration and transcription duty',
    },
  },
  {
    id: 'w2-tue', layout: 'system', track: 'trade',
    media: 'media/lumina-dudelange.png',
    fr: {
      kicker: 'Semaine 2 · Le système',
      rubric: 'Prospection · Dudelange',
      head: ['7 015 bâtiments,', 'extrudés depuis la', 'donnée <em>publique</em>.'],
      standfirst: 'J’ai arrêté de prospecter sur une liste. Le territoire est devenu une carte sur laquelle on peut travailler.',
      rows: [
        ['Emprises de bâtiments', '7 015'],
        ['Source géométrie', 'OpenStreetMap, découpé aux limites communales'],
        ['Fond aérien', 'ACT — orthophoto officielle, CC0'],
        ['Hauteur d’extrusion', 'hauteur mappée, sinon nombre d’étages'],
        ['Si le service de tuiles tombe', 'le maillage local reste affiché', true],
      ],
      screenCap: 'Capture réelle. Le panneau prospects a été retiré : il contient des noms et des adresses de particuliers.',
      source: 'OpenStreetMap · Administration du cadastre et de la topographie (ACT)',
    },
    en: {
      kicker: 'Week 2 · The system',
      rubric: 'Prospecting · Dudelange',
      head: ['7,015 buildings,', 'extruded from', '<em>public</em> data.'],
      standfirst: 'I stopped prospecting from a list. The territory became a map you can actually work on.',
      rows: [
        ['Building footprints', '7,015'],
        ['Geometry source', 'OpenStreetMap, clipped to municipal bounds'],
        ['Aerial base layer', 'ACT — official orthophoto, CC0'],
        ['Extrusion height', 'mapped height, else floor count'],
        ['If the tile service drops', 'the local mesh stays visible', true],
      ],
      screenCap: 'Real capture. The prospect panel is removed: it contains private individuals’ names and addresses.',
      source: 'OpenStreetMap · Administration du cadastre et de la topographie (ACT)',
    },
  },
  {
    id: 'w2-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 2 · Comment je vérifie',
      rubric: 'Méthode · Prix au m²',
      head: ['Comment je lis un prix au m²', 'sans me tromper de', '<em>référence</em>.'],
      standfirst: 'Le même bien peut sembler cher ou bon marché selon la source qu’on regarde. Les deux sources disent des choses différentes, et c’est normal.',
      steps: [
        ['01', 'Savoir laquelle des deux sources on lit', 'Les portails donnent le prix demandé. L’Observatoire donne le prix notarié, agrégé et publié avec un trimestre de retard. Confondre les deux fausse tout.'],
        ['02', 'Traiter l’écart comme une information', 'À Esch il est d’environ 950 €/m². Ce n’est pas du bruit : c’est la marge de négociation structurelle du marché.'],
        ['03', 'Descendre à la zone', 'La fourchette communale va de 4 284 à 7 480 €/m². Un prix « dans la moyenne » ne veut rien dire tant qu’on ne sait pas dans quel quartier il se situe.'],
        ['04', 'Exiger que la prime se justifie', 'Un bien au-dessus de la moyenne notariée doit avoir une raison mesurable : classe énergétique, rénovation, étage, terrasse. Sinon c’est juste un prix optimiste.'],
      ],
      statement: 'Un prix au m² sans sa source et sans sa zone n’est pas un argument. C’est un chiffre.',
      source: 'Observatoire de l’Habitat (avril 2026) · immotop.lu (juillet 2026)',
    },
    en: {
      kicker: 'Week 2 · How I check',
      rubric: 'Method · Price per m²',
      head: ['How I read a price per m²', 'against the right', '<em>reference</em>.'],
      standfirst: 'The same property can look expensive or cheap depending which source you read. The two sources say different things, and that is normal.',
      steps: [
        ['01', 'Know which of the two you are reading', 'Portals give the asking price. The Observatoire gives the notarial price, aggregated and published a quarter late. Confusing them distorts everything.'],
        ['02', 'Treat the gap as information', 'In Esch it is roughly €950/m². That is not noise — it is the market’s structural negotiating margin.'],
        ['03', 'Go down to the zone', 'The commune ranges from €4,284 to €7,480/m². A price "around the average" means nothing until you know the neighbourhood.'],
        ['04', 'Make the premium justify itself', 'A property above the notarial average needs a measurable reason: energy class, renovation, floor, terrace. Otherwise it is simply an optimistic price.'],
      ],
      statement: 'A price per m² without its source and its zone is not an argument. It is a number.',
      source: 'Observatoire de l’Habitat (April 2026) · immotop.lu (July 2026)',
    },
  },
  {
    id: 'w2-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 2 · Lecture de marché',
      rubric: 'Esch-sur-Alzette · Par quartier',
      head: ['Dans une seule commune,', 'le rendement <em>double</em>.'],
      standfirst: 'Facteur 1,75 sur les prix, facteur 2 sur les loyers. Toute analyse fondée sur la moyenne communale est fausse pour un bien précis.',
      rows: [
        ['Al-Esch — 6 580 €/m², loyer 27,70 €', '5,05 %', true],
        ['Dellhéicht — 4 284 €/m², loyer 14,25 €', '3,99 %'],
        ['Belval-Université — 4 911 €/m², loyer 15,75 €', '3,85 %'],
        ['Fettmeth — 6 971 €/m², loyer 18,07 €', '3,11 %'],
        ['Grenz — 7 480 €/m², loyer 14,28 €', '2,29 %'],
      ],
      statement: 'Al-Esch est la seule zone où le prix monte encore et où le loyer est le double des autres. Belval-Université, qui porte tout le récit du Sud, se vend sous la moyenne communale.',
      source: 'immotop.lu, ventilation par zone (juillet 2026)',
    },
    en: {
      kicker: 'Week 2 · Market read',
      rubric: 'Esch-sur-Alzette · By neighbourhood',
      head: ['Inside one commune,', 'the yield <em>doubles</em>.'],
      standfirst: '1.75× on prices, 2× on rents. Any analysis built on the commune average is wrong for a specific property.',
      rows: [
        ['Al-Esch — €6,580/m², rent €27.70', '5.05 %', true],
        ['Dellhéicht — €4,284/m², rent €14.25', '3.99 %'],
        ['Belval-Université — €4,911/m², rent €15.75', '3.85 %'],
        ['Fettmeth — €6,971/m², rent €18.07', '3.11 %'],
        ['Grenz — €7,480/m², rent €14.28', '2.29 %'],
      ],
      statement: 'Al-Esch is the only zone where prices still rise and rent is double everywhere else. Belval-Université, which carries the whole southern narrative, sells below the commune average.',
      source: 'immotop.lu, breakdown by zone (July 2026)',
    },
  },
  {
    id: 'w2-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 2 · Note de build',
      rubric: 'Ce que j’ai corrigé cette semaine',
      head: ['La moyenne communale est', 'le mensonge le plus', '<em>courant</em> du métier.'],
      standfirst: 'Le système refuse désormais de produire une estimation tant que la zone n’est pas renseignée.',
      statement: 'Ce n’est pas une contrainte technique. C’est la seule façon d’empêcher une analyse d’avoir l’air juste alors qu’elle est fausse d’un facteur deux.',
      rows: [
        ['Écart de prix entre zones', 'facteur 1,75'],
        ['Écart de loyer entre zones', 'facteur 2,0'],
        ['Ce que produit une analyse sans zone', 'un intervalle, pas un prix', true],
        ['Ce qu’il faut fournir', 'le quartier, pas seulement la commune'],
      ],
      source: 'immotop.lu, ventilation par zone · Observatoire de l’Habitat',
    },
    en: {
      kicker: 'Week 2 · Build note',
      rubric: 'What I fixed this week',
      head: ['The commune average is', 'this industry’s most', '<em>common</em> lie.'],
      standfirst: 'The system now refuses to produce a valuation until the zone is supplied.',
      statement: 'That is not a technical constraint. It is the only way to stop an analysis looking right while being wrong by a factor of two.',
      rows: [
        ['Price spread between zones', '1.75×'],
        ['Rent spread between zones', '2.0×'],
        ['What a zoneless analysis returns', 'a range, not a price', true],
        ['What you have to supply', 'the neighbourhood, not just the commune'],
      ],
      source: 'immotop.lu, breakdown by zone · Observatoire de l’Habitat',
    },
  },

  // ══ WEEK 3 ════════════════════════════════════════════════════════════
  {
    id: 'w3-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 3 · Le chiffre',
      rubric: 'Location · Plafond légal',
      head: ['Le loyer légal ne dépend', 'pas du bien. Il dépend de', 'ce que vous avez <em>payé</em>.'],
      standfirst: 'La loi du 21 septembre 2006 plafonne le loyer annuel à 5 % du capital investi réévalué. Pas de la qualité du bien, pas du marché.',
      figure: '5 %', unit: 'du capital',
      note: 'Rénover ne relève pas le plafond. Améliorer la classe énergétique non plus. Le seul levier légal, c’est ce que vous avez payé à l’achat.',
      rows: [
        ['Capital investi (bien à 545 000 €)', '588 600 €'],
        ['Plafond en vigueur — 5 %', '2 452 €/mois'],
        ['Projet de loi 8184 — 3,5 %', '1 717 €/mois'],
        ['Perte mensuelle si le texte passe', '−736 €', true],
      ],
      source: 'Loi du 21/09/2006 · projet de loi n°8184, non voté (chd.lu)',
    },
    en: {
      kicker: 'Week 3 · The number',
      rubric: 'Letting · The statutory cap',
      head: ['Legal rent does not depend', 'on the property. It depends', 'on what you <em>paid</em>.'],
      standfirst: 'The law of 21 September 2006 caps annual rent at 5 % of revalued invested capital. Not property quality, not the market.',
      figure: '5 %', unit: 'of capital',
      note: 'Renovating does not raise the cap. Nor does improving the energy class. The only legal lever is what you paid at purchase.',
      rows: [
        ['Invested capital (€545,000 property)', '€588,600'],
        ['Current cap — 5 %', '€2,452/month'],
        ['Draft law 8184 — 3.5 %', '€1,717/month'],
        ['Monthly loss if it passes', '−€736', true],
      ],
      source: 'Law of 21/09/2006 · draft law no. 8184, not passed (chd.lu)',
    },
  },
  {
    id: 'w3-tue', layout: 'read', track: 'trade',
    fr: {
      kicker: 'Semaine 3 · Le système',
      rubric: 'Analyse · Ce que produit une commande',
      head: ['Une analyse complète,', 'en une <em>commande</em>.'],
      standfirst: 'Ce qui me prenait une demi-journée en tableur sort maintenant structuré, sourcé, et avec ses incertitudes marquées.',
      rows: [
        ['Score composite', 'pondéré sur 5 catégories'],
        ['Comparables', 'annonces actives, surface et CPE relevées'],
        ['Cash-flow', 'NOI, service de la dette, DSCR'],
        ['Coûts d’acquisition', 'droits, notaire, Bëllegen Akt'],
        ['Chiffres non vérifiables', 'marqués, jamais estimés', true],
      ],
      statement: 'La sortie la plus utile n’est pas le score. C’est la liste des vérifications à faire avant de faire une offre.',
      source: 'Système interne — sources Observatoire · STATEC · BCL · pfi.public.lu',
    },
    en: {
      kicker: 'Week 3 · The system',
      rubric: 'Analysis · What one command returns',
      head: ['A full analysis,', 'in one <em>command</em>.'],
      standfirst: 'What used to take me half a day in a spreadsheet now comes out structured, sourced, and with its uncertainties marked.',
      rows: [
        ['Composite score', 'weighted across 5 categories'],
        ['Comparables', 'live listings, floor area and energy class captured'],
        ['Cash-flow', 'NOI, debt service, DSCR'],
        ['Acquisition costs', 'duty, notary, Bëllegen Akt'],
        ['Unverifiable figures', 'flagged, never estimated', true],
      ],
      statement: 'The most useful output is not the score. It is the list of checks to run before making an offer.',
      source: 'Internal system — sources Observatoire · STATEC · BCL · pfi.public.lu',
    },
  },
  {
    id: 'w3-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 3 · Comment je vérifie',
      rubric: 'Méthode · Investissement locatif',
      head: ['Baisser le prix ne sauve', 'pas un locatif. Voici', '<em>pourquoi</em>.'],
      standfirst: 'C’est la spécificité luxembourgeoise que les modèles anglo-saxons ne prévoient pas, et elle change complètement le raisonnement.',
      steps: [
        ['01', 'Le plafond suit le capital investi', 'Le loyer légal est proportionnel à ce que vous avez payé. Ailleurs, le loyer dépend du marché ; ici, il dépend de votre prix d’achat.'],
        ['02', 'Négocier baisse aussi le loyer autorisé', 'Payer 90 000 € de moins réduit le plafond dans la même proportion. Vous gagnez sur la mensualité et vous perdez sur le revenu.'],
        ['03', 'Vérifier au lieu de supposer', 'Sur un dossier réel : à 545 000 € le cash-flow est de −426 €. À 455 000 €, il reste négatif à environ −345 €. La baisse n’efface pas le problème.'],
        ['04', 'Les vrais leviers sont ailleurs', 'Seuls l’apport et le taux déplacent l’équilibre. Il faudrait environ 35 % d’apport, ou un taux sous 2,7 %.'],
      ],
      statement: 'Aucun prix d’achat n’équilibre cette opération à 80 % de LTV sur 25 ans. Ce n’est pas une question de négociation.',
      source: 'Loi du 21/09/2006 · BCL, taux moyen janvier 2026 · analyse Niederkorn',
    },
    en: {
      kicker: 'Week 3 · How I check',
      rubric: 'Method · Buy-to-let',
      head: ['Cutting the price does not', 'save a rental. Here is', '<em>why</em>.'],
      standfirst: 'This is the Luxembourg specificity that Anglo-Saxon models do not account for, and it changes the reasoning completely.',
      steps: [
        ['01', 'The cap follows invested capital', 'Legal rent is proportional to what you paid. Elsewhere rent depends on the market; here it depends on your purchase price.'],
        ['02', 'Negotiating also lowers permitted rent', 'Paying €90,000 less cuts the cap by the same proportion. You gain on the mortgage and lose on the income.'],
        ['03', 'Check instead of assuming', 'On a real file: at €545,000 cash-flow is −€426. At €455,000 it is still negative, around −€345. The discount does not remove the problem.'],
        ['04', 'The real levers are elsewhere', 'Only the deposit and the rate move the balance. You would need roughly 35 % down, or a rate below 2.7 %.'],
      ],
      statement: 'No purchase price balances this deal at 80 % LTV over 25 years. It is not a negotiation problem.',
      source: 'Law of 21/09/2006 · BCL average rate January 2026 · Niederkorn analysis',
    },
  },
  {
    id: 'w3-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 3 · Lecture de marché',
      rubric: 'Financement · Janvier 2026',
      head: ['3,01 %. Le chiffre qui a fait', 'la correction, et qui la', '<em>termine</em>.'],
      standfirst: 'La direction des taux explique l’essentiel du marché depuis 2022. Leur stabilisation autour de 3 % explique le creux d’avril et la reprise des volumes.',
      rows: [
        ['Taux moyen, nouveaux crédits', '3,01 %', true],
        ['Variation sur un mois', '−14 points de base'],
        ['Fixation 1–5 ans', '3,27 %'],
        ['Fixation 5–10 ans', '3,52 %'],
        ['Taux publié par les banques', 'aucun — prix personnalisé'],
      ],
      statement: 'À 3 %, la demande solvable tient. Un retour vers 3,5 % ramènerait la pression baissière ; une descente sous 2,75 % déclencherait probablement le rebond.',
      source: 'Banque centrale du Luxembourg, statistiques MIR (communiqué mars 2026)',
    },
    en: {
      kicker: 'Week 3 · Market read',
      rubric: 'Financing · January 2026',
      head: ['3.01 %. The number that', 'drove the correction, and', '<em>ends</em> it.'],
      standfirst: 'Rate direction explains most of this market since 2022. Stabilising around 3 % explains the April trough and the recovery in volumes.',
      rows: [
        ['Average rate, new lending', '3.01 %', true],
        ['Change over one month', '−14 basis points'],
        ['1–5 year fixation', '3.27 %'],
        ['5–10 year fixation', '3.52 %'],
        ['Rate published by banks', 'none — priced per profile'],
      ],
      statement: 'At 3 %, solvent demand holds. A return towards 3.5 % restores downward pressure; a fall below 2.75 % would probably trigger the rebound.',
      source: 'Banque centrale du Luxembourg, MIR statistics (March 2026 release)',
    },
  },
  {
    id: 'w3-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 3 · Note de build',
      rubric: 'Ce que j’ai ajouté cette semaine',
      head: ['Le simulateur calcule', 'les deux <em>régimes</em>.'],
      standfirst: 'Tant que la loi 8184 n’est pas votée, une analyse locative qui ne montre qu’un seul scénario est incomplète.',
      statement: 'Le texte est en discussion, non voté, non rétroactif. Mais il concerne tout nouveau bail. L’ignorer dans une projection à dix ans n’est pas une simplification, c’est une omission.',
      rows: [
        ['Régime en vigueur', '5 % du capital investi'],
        ['Régime proposé', '3,5 %'],
        ['Impact type, bien à 545 000 €', '−736 €/mois', true],
        ['Statut du texte', 'en discussion à la Chambre, non voté'],
      ],
      source: 'chd.lu · legilux.public.lu — projet de loi n°8184',
    },
    en: {
      kicker: 'Week 3 · Build note',
      rubric: 'What I added this week',
      head: ['The simulator now runs', 'both <em>regimes</em>.'],
      standfirst: 'Until law 8184 is voted on, a rental analysis showing only one scenario is incomplete.',
      statement: 'The text is under discussion, not passed, not retroactive. But it applies to every new lease. Ignoring it in a ten-year projection is not a simplification, it is an omission.',
      rows: [
        ['Current regime', '5 % of invested capital'],
        ['Proposed regime', '3.5 %'],
        ['Typical impact, €545,000 property', '−€736/month', true],
        ['Status', 'under discussion in the Chamber, not passed'],
      ],
      source: 'chd.lu · legilux.public.lu — draft law no. 8184',
    },
  },

  // ══ WEEK 4 ════════════════════════════════════════════════════════════
  {
    id: 'w4-mon', layout: 'figure', track: 'public',
    fr: {
      kicker: 'Semaine 4 · Le chiffre',
      rubric: 'Méthode · Ce qui n’existe pas',
      head: ['Quatre chiffres que', 'le Luxembourg ne', '<em>publie pas</em>.'],
      standfirst: 'Quand vous les voyez cités avec deux décimales, ils sont inventés. La donnée n’existe pas.',
      figure: '0', unit: 'registre public',
      note: 'Pas de MLS, pas de registre des prix de transaction. Un analyste honnête vous dit ce qu’il ne sait pas — c’est même à ça qu’on le reconnaît.',
      rows: [
        ['Ratio prix de vente / prix affiché', 'impossible'],
        ['% vendu au-dessus du prix affiché', 'impossible'],
        ['Délai de vente moyen', 'non publié'],
        ['Mois de stock par commune', 'non publié', true],
      ],
      source: 'Observatoire de l’Habitat · STATEC · Chambre Immobilière',
    },
    en: {
      kicker: 'Week 4 · The number',
      rubric: 'Method · What does not exist',
      head: ['Four numbers Luxembourg', 'does not <em>publish</em>.'],
      standfirst: 'When you see them quoted to two decimal places, they are invented. The underlying data does not exist.',
      figure: '0', unit: 'public registers',
      note: 'No MLS, no register of transaction prices. An honest analyst tells you what they do not know — it is how you spot one.',
      rows: [
        ['Sale-to-list price ratio', 'impossible'],
        ['% sold above asking', 'impossible'],
        ['Average days on market', 'not published'],
        ['Months of inventory by commune', 'not published', true],
      ],
      source: 'Observatoire de l’Habitat · STATEC · Chambre Immobilière',
    },
  },
  {
    id: 'w4-tue', layout: 'read', track: 'trade',
    fr: {
      kicker: 'Semaine 4 · Le système',
      rubric: 'Veille · Surveillance continue',
      head: ['Je surveille le marché', 'en continu, pas quand', 'j’en ai <em>besoin</em>.'],
      standfirst: 'Le problème d’un marché sans registre, ce n’est pas seulement l’absence de données. C’est que les annonces disparaissent sans laisser de trace.',
      rows: [
        ['Ce qui est capturé', 'annonce, prix, surface, CPE, agence'],
        ['Fréquence', 'en continu, pas à la demande'],
        ['Ce que ça permet', 'suivre un prix qui bouge, ou une annonce retirée'],
        ['Annonces dépubliées', 'exclues des comparables, jamais silencieusement', true],
      ],
      statement: 'Sur une analyse récente, deux comparables avaient été retirés du marché — HTTP 410 et 404. Ils sont sortis du calcul. Les garder aurait été plus flatteur et moins vrai.',
      source: 'Système interne · athome.lu · immotop.lu',
    },
    en: {
      kicker: 'Week 4 · The system',
      rubric: 'Monitoring · Continuous',
      head: ['I watch the market', 'continuously, not when', 'I <em>need</em> it.'],
      standfirst: 'The problem with a market that has no register is not only missing data. It is that listings vanish without leaving a trace.',
      rows: [
        ['What is captured', 'listing, price, area, energy class, agency'],
        ['Frequency', 'continuous, not on demand'],
        ['What that enables', 'tracking a price that moves, or a listing pulled'],
        ['Delisted properties', 'excluded from comparables, never silently', true],
      ],
      statement: 'On a recent analysis two comparables had been pulled — HTTP 410 and 404. They came out of the calculation. Keeping them would have been more flattering and less true.',
      source: 'Internal system · athome.lu · immotop.lu',
    },
  },
  {
    id: 'w4-wed', layout: 'method', track: 'public',
    fr: {
      kicker: 'Semaine 4 · Comment je vérifie',
      rubric: 'Méthode · Travailler sans MLS',
      head: ['Comment on travaille', 'un marché sans <em>MLS</em>.'],
      standfirst: 'Les réflexes de due diligence venus des États-Unis, du Royaume-Uni ou de France ne se transposent pas ici. La couche de données est plus mince.',
      steps: [
        ['01', 'Deux sources, jamais une', 'Prix affichés d’un côté, prix notariés agrégés de l’autre. Ce sont deux natures de chiffre. On ne les mélange pas, on les confronte.'],
        ['02', 'Dater chaque chiffre', 'L’Observatoire publie par trimestre avec du décalage. Un chiffre sans sa date est inutilisable dans une négociation.'],
        ['03', 'Marquer ce qu’on ignore', 'Zone non confirmée, CPE provisoire, chômage communal périmé. Une incertitude signalée reste exploitable ; une incertitude cachée ne l’est pas.'],
        ['04', 'Le notaire tranche', 'Bëllegen Akt, régime de plus-value, plafonds de déduction : les montants bougent. Aucune projection ne remplace une confirmation.'],
      ],
      statement: 'Il faut prévoir plus de temps sur les comparables locaux, et accorder moins de confiance aux tableaux de bord.',
      source: 'Observatoire de l’Habitat · STATEC · pfi.public.lu · impotsdirects.public.lu',
    },
    en: {
      kicker: 'Week 4 · How I check',
      rubric: 'Method · Working without an MLS',
      head: ['How you work a market', 'with no <em>MLS</em>.'],
      standfirst: 'Due diligence habits brought from the US, the UK or France do not transfer here. The data layer is thinner.',
      steps: [
        ['01', 'Two sources, never one', 'Asking prices on one side, aggregated notarial prices on the other. They are different kinds of number. You do not blend them, you compare them.'],
        ['02', 'Date every figure', 'The Observatoire publishes quarterly with a lag. A number without its date is unusable in a negotiation.'],
        ['03', 'Mark what you do not know', 'Unconfirmed zone, provisional energy certificate, stale unemployment data. A flagged uncertainty is still usable; a hidden one is not.'],
        ['04', 'The notary decides', 'Bëllegen Akt, capital gains regime, deduction caps — the amounts move. No projection replaces a confirmation.'],
      ],
      statement: 'Budget more time for local comparables, and less faith in dashboards.',
      source: 'Observatoire de l’Habitat · STATEC · pfi.public.lu · impotsdirects.public.lu',
    },
  },
  {
    id: 'w4-thu', layout: 'read', track: 'public',
    fr: {
      kicker: 'Semaine 4 · Lecture de marché',
      rubric: 'National · T1 2026',
      head: ['Le neuf recule.', 'La revente <em>repart</em>.'],
      standfirst: 'Deux marchés qui divergent dans le même trimestre. Pour un acheteur, ça change ce qu’il faut regarder ; pour un promoteur, ça change la façon de présenter un programme.',
      rows: [
        ['VEFA — 207 transactions', '−18,2 %', true],
        ['Appartements existants — 968', '+9,4 %'],
        ['Maisons existantes — 650', '+11,5 %'],
        ['Indice hédonique national, 12 mois', '+1,7 %'],
        ['— maisons existantes', '+3,0 %'],
        ['— appartements existants', '+0,9 %'],
      ],
      statement: 'L’offre neuve est sous pression pendant que la revente redémarre. À 12–24 mois, moins de neuf livré soutient mécaniquement l’existant.',
      source: 'Observatoire de l’Habitat / STATEC, rapport d’analyse n°25 (25/06/2026)',
    },
    en: {
      kicker: 'Week 4 · Market read',
      rubric: 'National · Q1 2026',
      head: ['New-build is falling.', 'Resale is <em>recovering</em>.'],
      standfirst: 'Two markets diverging in the same quarter. For a buyer it changes what to look at; for a developer it changes how a programme has to be presented.',
      rows: [
        ['Off-plan — 207 transactions', '−18.2 %', true],
        ['Existing apartments — 968', '+9.4 %'],
        ['Existing houses — 650', '+11.5 %'],
        ['National hedonic index, 12 months', '+1.7 %'],
        ['— existing houses', '+3.0 %'],
        ['— existing apartments', '+0.9 %'],
      ],
      statement: 'New supply is under pressure while resale restarts. At 12–24 months, less new-build delivered mechanically supports existing stock.',
      source: 'Observatoire de l’Habitat / STATEC, analysis report no. 25 (25/06/2026)',
    },
  },
  {
    id: 'w4-fri', layout: 'note', track: 'trade',
    fr: {
      kicker: 'Semaine 4 · Note de build',
      rubric: 'La règle qui tient tout',
      head: ['Chaque chiffre porte', 'sa source, ou il ne', '<em>sort pas</em>.'],
      standfirst: 'C’est la seule règle du système qui n’a jamais bougé, et c’est celle qui a le plus de conséquences.',
      statement: 'Un chiffre sourcé invite le lecteur à vérifier. C’est exactement pour ça qu’il faut le sourcer — et exactement pour ça qu’un chiffre périmé est pire que pas de chiffre du tout.',
      rows: [
        ['Sources câblées', 'Observatoire · STATEC · BCL · pfi · AED'],
        ['Chiffre sans source', 'refusé à la sortie'],
        ['Chiffre invérifiable', 'marqué « non vérifié »'],
        ['Chiffre périmé', 'marqué avec sa date', true],
      ],
      source: 'Règle interne. Appliquée aussi à ce que je publie ici.',
    },
    en: {
      kicker: 'Week 4 · Build note',
      rubric: 'The rule that holds it together',
      head: ['Every number carries', 'its source, or it does', 'not <em>ship</em>.'],
      standfirst: 'It is the one rule in the system that has never moved, and the one with the most consequences.',
      statement: 'A sourced number invites the reader to check. That is exactly why you source it — and exactly why a stale number is worse than no number at all.',
      rows: [
        ['Sources wired in', 'Observatoire · STATEC · BCL · pfi · AED'],
        ['Number without a source', 'refused at output'],
        ['Unverifiable number', 'marked "unverified"'],
        ['Stale number', 'marked with its date', true],
      ],
      source: 'Internal rule. Applied to what I publish here too.',
    },
  },
];
