// Ayrton Silva — infographics. Three layouts: board · waterfall · ladder.
// Figures: PROPERTY-MARKET-Sud-4-communes.md + Esch/Niederkorn analyses.
// Reference period July 2026, gathered 10/08/2026.

export const GRAPHICS = [
  {
    id: 'carte-du-sud', layout: 'board', track: 'public',
    fr: {
      kicker: 'Infographie · Ceinture Sud',
      rubric: 'Juillet 2026',
      head: ['La carte du Sud,', 'en <em>chiffres</em>.'],
      standfirst: 'Six communes voisines, trois vitesses de marché. Prix affichés — le Luxembourg ne publie pas les prix de vente.',
      cols: ['Prix €/m²', 'Sur 1 an', 'Loyer €/m²', 'Vente : loc.'],
      rows: [
        ['Esch-sur-Alzette', ['7 149', '−1,31 %', '28,17', '17,6 : 1'], []],
        ['Bettembourg', ['7 070', '−3,64 %', '22,97', '22,3 : 1'], [1]],
        ['Sanem', ['6 773', '−2,99 %', '25,38', '46,2 : 1'], []],
        ['Dudelange', ['6 628', '+0,52 %', '25,76', '50,8 : 1'], [3]],
        ['Differdange', ['6 317', '−0,91 %', '28,27', '30 : 1'], []],
        ['Pétange', ['6 276', '+0,18 %', '25,85', '27,4 : 1'], []],
      ],
      takeaway: 'Bettembourg corrige le plus vite. Dudelange a le déséquilibre locatif le plus extrême du pays que j’aie mesuré.',
      source: 'immotop.lu, séries communales (juillet 2026) · Observatoire de l’Habitat',
    },
    en: {
      kicker: 'Infographic · Southern belt',
      rubric: 'July 2026',
      head: ['The south,', 'in <em>numbers</em>.'],
      standfirst: 'Six neighbouring communes, three market speeds. Asking prices — Luxembourg does not publish sale prices.',
      cols: ['Price €/m²', '1 year', 'Rent €/m²', 'Sale : rent'],
      rows: [
        ['Esch-sur-Alzette', ['7,149', '−1.31 %', '28.17', '17.6 : 1'], []],
        ['Bettembourg', ['7,070', '−3.64 %', '22.97', '22.3 : 1'], [1]],
        ['Sanem', ['6,773', '−2.99 %', '25.38', '46.2 : 1'], []],
        ['Dudelange', ['6,628', '+0.52 %', '25.76', '50.8 : 1'], [3]],
        ['Differdange', ['6,317', '−0.91 %', '28.27', '30 : 1'], []],
        ['Pétange', ['6,276', '+0.18 %', '25.85', '27.4 : 1'], []],
      ],
      takeaway: 'Bettembourg is correcting fastest. Dudelange has the most extreme rental imbalance I have measured in the country.',
      source: 'immotop.lu communal series (July 2026) · Observatoire de l’Habitat',
    },
  },
  {
    id: 'vrai-cout', layout: 'waterfall', track: 'public',
    fr: {
      kicker: 'Infographie · Coût d’acquisition',
      rubric: 'Résidence principale vs locatif',
      head: ['Ce que 545 000 €', 'coûtent <em>vraiment</em>.'],
      standfirst: 'Le prix affiché n’est pas le capital engagé. Et l’usage du bien change tout.',
      steps: [
        ['Prix du bien', '545 000 €', 545000],
        ['+ Droits d’enregistrement 6 %', '32 700 €', 32700],
        ['+ Droit de transcription 1 %', '5 450 €', 5450],
        ['+ Notaire ~1 %', '5 450 €', 5450],
      ],
      total: ['Capital réellement investi', '588 600 €'],
      split: [
        ['Résidence principale', '~5 450 € de cash', 'Bëllegen Akt : jusqu’à 40 000 € de droits effacés par acquéreur'],
        ['Investissement locatif', '~152 600 € de cash', 'Pas de Bëllegen Akt + apport de 20 % exigé'],
      ],
      takeaway: 'Même bien, deux opérations. Trente fois plus de liquide en locatif.',
      source: 'pfi.public.lu — droits et Bëllegen Akt (loi du 03/07/2025) · barème notarial',
    },
    en: {
      kicker: 'Infographic · Acquisition cost',
      rubric: 'Primary residence vs buy-to-let',
      head: ['What €545,000', '<em>really</em> costs.'],
      standfirst: 'The asking price is not the capital committed. And the property’s use changes everything.',
      steps: [
        ['Property price', '€545,000', 545000],
        ['+ Registration duty 6 %', '€32,700', 32700],
        ['+ Transcription duty 1 %', '€5,450', 5450],
        ['+ Notary ~1 %', '€5,450', 5450],
      ],
      total: ['Capital actually invested', '€588,600'],
      split: [
        ['Primary residence', '~€5,450 cash', 'Bëllegen Akt: up to €40,000 of duty erased per buyer'],
        ['Buy-to-let', '~€152,600 cash', 'No Bëllegen Akt + 20 % deposit required'],
      ],
      takeaway: 'Same property, two operations. Thirty times more cash as a rental.',
      source: 'pfi.public.lu — duty and Bëllegen Akt (law of 03/07/2025) · notarial scale',
    },
  },
  {
    id: 'echelle-esch', layout: 'ladder', track: 'public',
    fr: {
      kicker: 'Infographie · Esch-sur-Alzette',
      rubric: 'Prix et rendement par quartier',
      head: ['Une commune,', 'un facteur <em>1,75</em>.'],
      standfirst: 'Le prix au m² et le rendement brut changent du simple au double selon le quartier. La moyenne communale ne décrit aucun d’entre eux.',
      max: 7480,
      rungs: [
        ['Grenz', 7480, '2,29 %', false],
        ['Fettmeth', 6971, '3,11 %', false],
        ['Al-Esch', 6580, '5,05 %', true],
        ['Park', 6439, '3,13 %', false],
        ['Lankelz', 5537, '3,28 %', false],
        ['Bruch', 5410, '3,50 %', false],
        ['Neiduerf', 5144, '3,68 %', false],
        ['Belval-Université', 4911, '3,85 %', false],
        ['Brill', 4660, '3,71 %', false],
        ['Dellhéicht', 4284, '3,99 %', false],
      ],
      legend: ['€/m² affiché', 'rendement brut'],
      takeaway: 'Al-Esch est le seul quartier où le prix monte encore et où le rendement approche 5 %. Le plus cher (Grenz) rend le moins.',
      source: 'immotop.lu, ventilation par zone (juillet 2026)',
    },
    en: {
      kicker: 'Infographic · Esch-sur-Alzette',
      rubric: 'Price and yield by neighbourhood',
      head: ['One commune,', 'a <em>1.75×</em> spread.'],
      standfirst: 'Price per m² and gross yield double depending on the neighbourhood. The commune average describes none of them.',
      max: 7480,
      rungs: [
        ['Grenz', 7480, '2.29 %', false],
        ['Fettmeth', 6971, '3.11 %', false],
        ['Al-Esch', 6580, '5.05 %', true],
        ['Park', 6439, '3.13 %', false],
        ['Lankelz', 5537, '3.28 %', false],
        ['Bruch', 5410, '3.50 %', false],
        ['Neiduerf', 5144, '3.68 %', false],
        ['Belval-Université', 4911, '3.85 %', false],
        ['Brill', 4660, '3.71 %', false],
        ['Dellhéicht', 4284, '3.99 %', false],
      ],
      legend: ['€/m² asking', 'gross yield'],
      takeaway: 'Al-Esch is the only neighbourhood still rising and the only one approaching a 5 % yield. The dearest (Grenz) yields the least.',
      source: 'immotop.lu, breakdown by zone (July 2026)',
    },
  },
];
