// IDEPUB — "Les chiffres du marché luxembourgeois" / "Luxembourg market numbers"
// Every figure traces to a named public source. No invented metrics.
// Source data: property-analyses/ (verified 05/08/2026).
// Brandkit rule enforced: idepub-brandkit/SKILL.md line 47.

export const POSTS = [
  {
    n: 1,
    fr: {
      eyebrow: "Marché immobilier · Luxembourg",
      head: ["Ce que les vendeurs", "demandent, et ce qui", "se <em>paie</em>."],
      figure: "950 €",
      figureUnit: "/m²",
      figureCaption: "L'écart entre prix affiché et prix notarié à Esch-sur-Alzette",
      rows: [
        ["Prix affiché moyen", "7 149 €/m²"],
        ["Prix notarié moyen", "~6 200 €/m²"],
        ["Écart", "950 €/m²"],
      ],
      body: "Sur un appartement affiché à 600 000 €, il existe une marge structurelle qui ne dépend pas de votre talent de négociateur. Elle est dans le marché.",
      source: "Observatoire de l'Habitat (avril 2026) · immotop.lu (juillet 2026)",
    },
    en: {
      eyebrow: "Property market · Luxembourg",
      head: ["What sellers ask,", "and what actually", "gets <em>paid</em>."],
      figure: "€950",
      figureUnit: "/m²",
      figureCaption: "The gap between asking and notarial price in Esch-sur-Alzette",
      rows: [
        ["Average asking price", "€7,149/m²"],
        ["Average notarial price", "~€6,200/m²"],
        ["Gap", "€950/m²"],
      ],
      body: "On an apartment listed at €600,000, there is a structural margin that has nothing to do with how good a negotiator you are. It is in the market.",
      source: "Observatoire de l'Habitat (April 2026) · immotop.lu (July 2026)",
    },
  },
  {
    n: 2,
    fr: {
      eyebrow: "Tendance des prix",
      head: ["La correction est", "réelle. Le gain de la", "décennie est <em>intact</em>."],
      figure: "+47,1 %",
      figureUnit: "",
      figureCaption: "Prix affichés à Esch-sur-Alzette depuis 2019",
      rows: [
        ["Depuis le pic de janvier 2026", "−5,4 %"],
        ["Sur 3 ans", "−6,3 %"],
        ["Depuis 2019", "+47,1 %"],
      ],
      body: "Ceux qui ont acheté en 2019 vont très bien. Ceux qui ont acheté en 2022 attendent. Les deux affirmations sont vraies en même temps.",
      source: "immotop.lu, série Esch-sur-Alzette (juillet 2026)",
    },
    en: {
      eyebrow: "Price trend",
      head: ["The correction is real.", "The decade's gain is", "<em>intact</em>."],
      figure: "+47.1%",
      figureUnit: "",
      figureCaption: "Asking prices in Esch-sur-Alzette since 2019",
      rows: [
        ["Since the January 2026 peak", "−5.4%"],
        ["Over 3 years", "−6.3%"],
        ["Since 2019", "+47.1%"],
      ],
      body: "Anyone who bought in 2019 is fine. Anyone who bought in 2022 is waiting. Both things are true at the same time.",
      source: "immotop.lu, Esch-sur-Alzette series (July 2026)",
    },
  },
  {
    n: 3,
    fr: {
      eyebrow: "Offre et demande",
      head: ["792 biens à vendre.", "45 à louer. Le même", "<em>marché</em>."],
      figure: "17,6",
      figureUnit: ": 1",
      figureCaption: "Ratio vente / location à Esch-sur-Alzette",
      rows: [
        ["Biens à la vente", "792"],
        ["Biens à la location", "45"],
        ["Population communale", "37 922"],
      ],
      body: "Ce n'est pas un accident. Le plafond légal de loyer — 5 % du capital investi — comprime le rendement au point que les propriétaires préfèrent vendre que louer.",
      source: "immotop.lu (juillet 2026) · loi du 21/09/2006",
    },
    en: {
      eyebrow: "Supply and demand",
      head: ["792 for sale.", "45 to rent. The same", "<em>market</em>."],
      figure: "17.6",
      figureUnit: ": 1",
      figureCaption: "Sale-to-rent ratio in Esch-sur-Alzette",
      rows: [
        ["Properties for sale", "792"],
        ["Properties to rent", "45"],
        ["Commune population", "37,922"],
      ],
      body: "This is not an accident. The statutory rent cap — 5% of invested capital — compresses yield to the point where owners prefer to sell rather than let.",
      source: "immotop.lu (July 2026) · law of 21/09/2006",
    },
  },
  {
    n: 4,
    fr: {
      eyebrow: "Géographie du prix",
      head: ["Dans une seule", "commune, le rendement", "<em>double</em>."],
      figure: "5,05 %",
      figureUnit: "",
      figureCaption: "Rendement brut à Al-Esch — contre 2,29 % à Grenz",
      rows: [
        ["Al-Esch", "6 580 €/m² · 27,70 € loyer"],
        ["Belval-Université", "4 911 €/m² · 15,75 € loyer"],
        ["Grenz", "7 480 €/m² · 14,28 € loyer"],
      ],
      body: "Facteur 1,75 sur les prix, 2,0 sur les loyers. À Esch, l'adresse compte plus que le bien. Toute analyse fondée sur la moyenne communale est fausse.",
      source: "immotop.lu, ventilation par zone (juillet 2026)",
    },
    en: {
      eyebrow: "The geography of price",
      head: ["Inside one commune,", "the yield", "<em>doubles</em>."],
      figure: "5.05%",
      figureUnit: "",
      figureCaption: "Gross yield in Al-Esch — against 2.29% in Grenz",
      rows: [
        ["Al-Esch", "€6,580/m² · €27.70 rent"],
        ["Belval-Université", "€4,911/m² · €15.75 rent"],
        ["Grenz", "€7,480/m² · €14.28 rent"],
      ],
      body: "1.75× on prices, 2.0× on rents. In Esch the address matters more than the property. Any analysis built on the commune average is wrong.",
      source: "immotop.lu, breakdown by zone (July 2026)",
    },
  },
  {
    n: 5,
    fr: {
      eyebrow: "Marché locatif",
      head: ["Les prix baissent.", "Les loyers sont au plus", "<em>haut</em>."],
      figure: "+30,8 %",
      figureUnit: "",
      figureCaption: "Loyers affichés à Esch-sur-Alzette sur 5 ans",
      rows: [
        ["Loyer moyen affiché", "28,17 €/m²/mois"],
        ["Sur 1 an", "+3,22 %"],
        ["Sur 5 ans", "+30,8 %"],
      ],
      body: "Prix en repli, loyers au plus haut historique. Pour un investisseur c'est la bonne direction — mais le plafond légal reprend d'une main ce que le marché donne de l'autre.",
      source: "immotop.lu (juillet 2026)",
    },
    en: {
      eyebrow: "Rental market",
      head: ["Prices are falling.", "Rents are at an", "all-time <em>high</em>."],
      figure: "+30.8%",
      figureUnit: "",
      figureCaption: "Asking rents in Esch-sur-Alzette over 5 years",
      rows: [
        ["Average asking rent", "€28.17/m²/month"],
        ["Over 1 year", "+3.22%"],
        ["Over 5 years", "+30.8%"],
      ],
      body: "Prices down, rents at a record. For an investor that is the right direction — but the statutory cap takes back with one hand what the market gives with the other.",
      source: "immotop.lu (July 2026)",
    },
  },
  {
    n: 6,
    fr: {
      eyebrow: "Financement",
      head: ["Le taux moyen est", "repassé sous les", "<em>3,1 %</em>."],
      figure: "3,01 %",
      figureUnit: "",
      figureCaption: "Taux moyen sur les nouveaux crédits immobiliers, janvier 2026",
      rows: [
        ["Variation sur un mois", "−14 points de base"],
        ["Fixation 1-5 ans", "3,27 %"],
        ["Fixation 5-10 ans", "3,52 %"],
      ],
      body: "C'est le principal moteur de la correction post-2022, et de sa fin. Aucune banque luxembourgeoise ne publie de taux fixe unique : le prix est personnalisé.",
      source: "Banque centrale du Luxembourg, statistiques MIR (mars 2026)",
    },
    en: {
      eyebrow: "Financing",
      head: ["The average rate is", "back below", "<em>3.1%</em>."],
      figure: "3.01%",
      figureUnit: "",
      figureCaption: "Average rate on new mortgage lending, January 2026",
      rows: [
        ["Change over one month", "−14 basis points"],
        ["1–5 year fixation", "3.27%"],
        ["5–10 year fixation", "3.52%"],
      ],
      body: "This is the main driver of the post-2022 correction, and of its end. No Luxembourg bank publishes a single fixed rate: pricing is personalised.",
      source: "Banque centrale du Luxembourg, MIR statistics (March 2026)",
    },
  },
  {
    n: 7,
    fr: {
      eyebrow: "Neuf contre ancien",
      head: ["La revente repart.", "Le neuf est sous", "<em>pression</em>."],
      figure: "−18,2 %",
      figureUnit: "",
      figureCaption: "Transactions VEFA au T1 2026, sur un an",
      rows: [
        ["VEFA", "207 transactions · −18,2 %"],
        ["Appartements existants", "968 · +9,4 %"],
        ["Maisons existantes", "650 · +11,5 %"],
      ],
      body: "Deux marchés qui divergent dans le même trimestre. Pour un promoteur, c'est le signal que la présentation du programme compte davantage qu'avant.",
      source: "Observatoire de l'Habitat / STATEC, rapport n°25 (25/06/2026)",
    },
    en: {
      eyebrow: "New-build vs existing",
      head: ["Resale is recovering.", "New-build is under", "<em>pressure</em>."],
      figure: "−18.2%",
      figureUnit: "",
      figureCaption: "Off-plan (VEFA) transactions in Q1 2026, year on year",
      rows: [
        ["VEFA (off-plan)", "207 transactions · −18.2%"],
        ["Existing apartments", "968 · +9.4%"],
        ["Existing houses", "650 · +11.5%"],
      ],
      body: "Two markets diverging in the same quarter. For a developer, that is the signal that how a programme is presented matters more than it used to.",
      source: "Observatoire de l'Habitat / STATEC, report no. 25 (25/06/2026)",
    },
  },
  {
    n: 8,
    fr: {
      eyebrow: "Coût réel d'acquisition",
      head: ["Un bien à 545 000 €", "vous coûte", "<em>588 600 €</em>."],
      figure: "43 600 €",
      figureUnit: "",
      figureCaption: "Frais d'acquisition sur un achat à 545 000 €",
      rows: [
        ["Droits d'enregistrement (6 %)", "32 700 €"],
        ["Droit de transcription (1 %)", "5 450 €"],
        ["Notaire (~1 %)", "5 450 €"],
      ],
      body: "C'est ce capital investi qui doit servir de base à tout calcul de rendement — jamais le prix affiché. L'erreur la plus fréquente des dossiers d'investissement.",
      source: "pfi.public.lu — droits d'enregistrement et de transcription",
    },
    en: {
      eyebrow: "Real acquisition cost",
      head: ["A €545,000 property", "costs you", "<em>€588,600</em>."],
      figure: "€43,600",
      figureUnit: "",
      figureCaption: "Acquisition costs on a €545,000 purchase",
      rows: [
        ["Registration duty (6%)", "€32,700"],
        ["Transcription duty (1%)", "€5,450"],
        ["Notary (~1%)", "€5,450"],
      ],
      body: "This invested capital is what every yield calculation should rest on — never the asking price. The most common error in investment files.",
      source: "pfi.public.lu — registration and transcription duty",
    },
  },
  {
    n: 9,
    fr: {
      eyebrow: "Méthode",
      head: ["Quatre chiffres qui", "n'existent pas au", "<em>Luxembourg</em>."],
      figure: "0",
      figureUnit: "",
      figureCaption: "Registre public des prix de transaction. Il n'y en a pas.",
      rows: [
        ["Ratio prix de vente / affiché", "impossible"],
        ["% vendu au-dessus du prix", "impossible"],
        ["Délai de vente moyen", "non publié"],
        ["Mois de stock par commune", "non publié"],
      ],
      body: "Pas de MLS, pas de registre public. Quand vous voyez ces métriques citées avec deux décimales, elles sont inventées. Un analyste honnête dit ce qu'il ne sait pas.",
      source: "Observatoire de l'Habitat · STATEC · Chambre Immobilière",
    },
    en: {
      eyebrow: "Method",
      head: ["Four numbers that", "do not exist in", "<em>Luxembourg</em>."],
      figure: "0",
      figureUnit: "",
      figureCaption: "Public registers of transaction prices. There are none.",
      rows: [
        ["Sale-to-list price ratio", "impossible"],
        ["% sold above asking", "impossible"],
        ["Average days on market", "not published"],
        ["Months of inventory by commune", "not published"],
      ],
      body: "No MLS, no public register. When you see these metrics quoted to two decimal places, they are invented. An honest analyst tells you what they don't know.",
      source: "Observatoire de l'Habitat · STATEC · Chambre Immobilière",
    },
  },
  {
    n: 10,
    fr: {
      eyebrow: "IDEPUB · Vidéo immobilière",
      head: ["Des chiffres sourcés.", "Des vidéos qui les", "<em>racontent</em>."],
      figure: "48h",
      figureUnit: "",
      figureCaption: "Délai de livraison standard IDEPUB",
      rows: [
        ["Pack Annonce", "un bien, un film"],
        ["Studio", "le programme complet"],
        ["Programme", "production continue"],
      ],
      body: "Nous produisons la vidéo immobilière pour les promoteurs, architectes et entreprises de construction au Luxembourg. Chaque chiffre de cette série est sourcé et vérifiable.",
      source: "Sources complètes de la série en légende de chaque publication",
      isCta: true,
      cta: 'Envoyer "DEMO"',
    },
    en: {
      eyebrow: "IDEPUB · Property video",
      head: ["Sourced numbers.", "Video that tells", "the <em>story</em>."],
      figure: "48h",
      figureUnit: "",
      figureCaption: "Standard IDEPUB delivery time",
      rows: [
        ["Pack Annonce", "one property, one film"],
        ["Studio", "the full programme"],
        ["Programme", "continuous production"],
      ],
      body: "We produce property video for developers, architects and construction firms in Luxembourg. Every figure in this series is sourced and verifiable.",
      source: "Full series sources in the caption of each post",
      isCta: true,
      cta: 'Send "DEMO"',
    },
  },
];
