// « Le rapport du Sud » — the gated flagship lead magnet.
// Every figure from PROPERTY-MARKET-Sud-4-communes.md and the Esch/Niederkorn
// analyses (immotop.lu July 2026, Observatoire April 2026, gathered 10/08/2026).
// House rule applies: nothing invented, unknowns stated.

export const DOC = {
  id: 'rapport-du-sud',
  fr: {
    docLabel: 'Le rapport du Sud · Édition août 2026',
    cover: {
      kicker: 'Marché immobilier · Ceinture Sud',
      title: 'Le rapport<br>du Sud.',
      sub: 'Six communes, les chiffres vérifiables, et ce que le Luxembourg ne publie pas. Esch-sur-Alzette · Differdange · Dudelange · Bettembourg · Sanem · Pétange.',
      band: [
        ['6', 'communes analysées'],
        ['1 641', 'annonces actives comptées'],
        ['50,8 : 1', 'le ratio vente/location à Dudelange'],
        ['0', 'chiffre inventé'],
      ],
      who: 'Ayrton Silva',
      what: 'Agent immobilier · Luxembourg — analyses sourcées, méthode vérifiable',
      date: 'Données de référence : juillet 2026 · relevées le 10/08/2026 · valables un trimestre',
    },
    pages: [
      {
        rubric: 'Méthode',
        h2: 'Ce que ce rapport refuse de faire',
        lede: 'Le Luxembourg ne publie ni registre des transactions, ni délai de vente, ni taux d’absorption. Ce rapport marque ces données comme absentes plutôt que de les estimer.',
        body: 'Les chiffres qui suivent reposent sur deux natures de source : les prix affichés (immotop.lu, athome.lu — ce que les vendeurs demandent) et les prix notariés agrégés de l’Observatoire de l’Habitat (ce qui se paie réellement, publié par trimestre avec décalage). L’écart entre les deux est lui-même une information : à Esch-sur-Alzette, il vaut environ 950 €/m².',
        table: {
          head: ['Métrique demandée par les modèles anglo-saxons', 'Statut au Luxembourg'],
          rows: [
            ['Prix de vente médian réel', 'impossible — aucun registre public'],
            ['Ratio prix de vente / prix affiché', 'impossible'],
            ['% vendu au-dessus du prix affiché', 'impossible'],
            ['Délai de vente moyen', 'non publié'],
            ['Mois de stock par commune', 'non publié'],
            ['Taux de vacance locative', 'non publié par commune'],
          ],
        },
        statement: 'Un analyste honnête vous dit ce qu’il ne sait pas. C’est même à ça qu’on le reconnaît.',
      },
      {
        rubric: 'Vue d’ensemble',
        h2: 'Six communes, trois vitesses',
        lede: 'Le Sud n’est pas un marché. En juillet 2026, des communes voisines vont dans des directions opposées.',
        table: {
          head: ['Commune', 'Prix affiché', 'Sur 1 an', 'Loyer', 'Loyer 1 an', 'Vente/loc.'],
          rows: [
            ['Esch-sur-Alzette', '7 149 €/m²', '−1,31 %', '28,17 €', '+3,22 %', '17,6 : 1'],
            ['Bettembourg', '7 070 €/m²', ['−3,64 %', true], '22,97 €', '+1,10 %', '22,3 : 1'],
            ['Sanem', '6 773 €/m²', '−2,99 %', '25,38 €', '+4,53 %', '46,2 : 1'],
            ['Dudelange', '6 628 €/m²', '+0,52 %', '25,76 €', ['+12,34 %', true], ['50,8 : 1', true]],
            ['Differdange (Niederkorn)', '6 317 €/m²', '−0,91 %', '28,27 €', '+7,53 %', '30 : 1'],
            ['Pétange', '6 276 €/m²', '+0,18 %', '25,85 €', '+8,61 %', '27,4 : 1'],
          ],
        },
        body: 'Bettembourg et Sanem corrigent depuis des pics récents (septembre et décembre 2025). Dudelange et Pétange ont déjà corrigé et se stabilisent. Esch et Differdange glissent doucement. Trois phases de cycle différentes, à quinze kilomètres d’écart.',
        note: 'Sources — immotop.lu, séries communales (juillet 2026) · Observatoire de l’Habitat (avril 2026). Prix affichés, pas prix de vente.',
      },
      {
        rubric: 'Le fait dominant',
        h2: 'La pénurie locative est un artefact juridique',
        lede: 'Partout dans le Sud, le stock à vendre écrase le stock à louer. Ce n’est pas la démographie — c’est la loi.',
        bigfig: ['254 / 5', ''],
        body: 'Dudelange compte 254 biens à vendre pour 5 à louer — le déséquilibre le plus extrême que j’aie mesuré au Luxembourg. Le plafond légal de loyer (5 % du capital investi réévalué, loi du 21/09/2006) comprime le rendement au point que les propriétaires arbitrent en faveur de la vente. Résultat mécanique : là où il y a le moins à louer, les loyers montent le plus vite. Dudelange affiche +12,34 % de loyer en un an.',
        table: {
          head: ['Commune', 'À vendre', 'À louer', 'Ratio', 'Loyer sur 1 an'],
          rows: [
            ['Dudelange', '254', '5', ['50,8 : 1', true], ['+12,34 %', true]],
            ['Sanem', '231', '5', '46,2 : 1', '+4,53 %'],
            ['Pétange', '274', '10', '27,4 : 1', '+8,61 %'],
            ['Bettembourg', '89', '4', '22,3 : 1', '+1,10 %'],
          ],
        },
        statement: 'Le projet de loi n°8184 ramènerait le plafond de 5 % à 3,5 % pour les nouveaux baux. Non voté, non rétroactif — et aucune décision locative sérieuse ne devrait être prise avant de connaître son sort.',
      },
      {
        rubric: 'La leçon d’échelle',
        h2: 'La moyenne communale est un mensonge statistique',
        lede: 'Dans le Sud de 2026, la dispersion entre localités d’une même commune dépasse la dispersion entre communes.',
        table: {
          head: ['Localité (commune)', '€/m²', 'Sur 1 an'],
          rows: [
            ['Belvaux (Sanem)', '6 926 €', ['+2,9 %', true]],
            ['Soleuvre (Sanem)', '6 741 €', '−5,7 %'],
            ['Ehlerange (Sanem)', '6 035 €', ['−11,0 %', true]],
            ['Fennange (Bettembourg)', '7 714 €', ['−10,6 %', true]],
            ['Abweiler (Bettembourg)', '7 187 €', '0,0 %'],
            ['Pétange localité', '6 297 €', '+1,3 %'],
            ['Lamadelaine (Pétange)', '6 054 €', '−5,2 %'],
          ],
        },
        body: 'Quatorze points d’écart en un an entre Belvaux et Ehlerange — dans la même commune de 25 km². Belvaux touche le campus de Belval ; Ehlerange en est le plus loin. À Bettembourg, deux localités perdent plus de 10 % pendant qu’une troisième ne bouge pas. À Esch, le rendement brut va de 2,29 % (Grenz) à 5,05 % (Al-Esch) selon le quartier.',
        statement: 'Toute décision prise sur une moyenne communale est prise sur un chiffre qui ne décrit aucune adresse réelle.',
      },
      {
        rubric: 'Le coût réel',
        h2: 'Un bien à 545 000 € engage 588 600 €',
        lede: 'Les frais d’acquisition ne sont pas une ligne annexe. Ils sont la base de tout calcul sérieux — et l’usage du bien change tout.',
        table: {
          head: ['Poste', 'Montant'],
          rows: [
            ['Prix du bien', '545 000 €'],
            ['Droits d’enregistrement (6 %)', '32 700 €'],
            ['Droit de transcription (1 %)', '5 450 €'],
            ['Notaire (~1 %)', '5 450 €'],
            ['Capital réellement investi', ['588 600 €', true]],
          ],
        },
        body: 'En résidence principale, le Bëllegen Akt efface jusqu’à 40 000 € de droits par acquéreur (montant confirmé par la loi du 03/07/2025 ; un communiqué du 16/07/2026 annonce 45 000 €, non consolidé au moment de la rédaction — à confirmer avec le notaire). Le cash à la signature tombe alors autour de 5 450 €. En locatif, le crédit ne s’applique pas : comptez environ 152 600 € de liquide sur ce même bien à 80 % de LTV.',
        statement: 'Acheter pour habiter et acheter pour louer, c’est le même bien et deux opérations qui n’ont rien à voir. Trente fois plus de cash dans le second cas.',
      },
      {
        rubric: 'Vos quatre vérifications',
        h2: 'Avant toute offre dans le Sud',
        lede: 'Aucune n’est spectaculaire. Ensemble, elles évitent la quasi-totalité des mauvaises surprises que j’ai vues arriver après signature.',
        checklist: [
          ['01 · Le passeport énergétique définitif', 'Pas le provisoire. Sur les comparables relevés à Esch, l’écart entre l’ancien non rénové et le rénové atteint +38 % au m². La prime repose sur un document — exigez-le.'],
          ['02 · Le budget du syndic et le fonds de réserve', 'Une copropriété de cinq lots répartit une toiture sur cinq quotes-parts au lieu de trente. La gouvernance est simple, la facture ne l’est pas.'],
          ['03 · Le zonage de la parcelle', 'PAG, PAP, zones inondables (l’Alzette et la Chiers traversent le bassin), et le CASIPO — cadastre des sites potentiellement pollués, incontournable sur un ancien bassin sidérurgique. Quinze minutes sur geoportail.lu.'],
          ['04 · Les montants fiscaux, auprès du notaire', 'Bëllegen Akt, régime de plus-value, plafonds de déduction : trois chiffres qui ont bougé récemment. Aucune simulation ne remplace une confirmation.'],
        ],
        statement: 'Ce ne sont pas des précautions d’investisseur. C’est le minimum pour un achat de résidence principale — et presque personne ne fait les quatre.',
      },
      {
        rubric: 'Sources et limites',
        h2: 'Vérifiez-moi',
        lede: 'Chaque chiffre de ce rapport porte sa source. Ce qui n’est pas publié au Luxembourg n’est pas estimé — c’est dit.',
        body: 'Prix et stocks : immotop.lu, séries communales, période de référence juillet 2026, relevés le 10/08/2026. Prix notariés : Observatoire de l’Habitat (avril 2026). Rail : cfl.lu et notices de gares. Écoles : lnbd.lu, lbv.lu, lma.lu. Cadre légal : loi du 21/09/2006 (plafond de loyer), loi du 03/07/2025 (Bëllegen Akt), projet de loi n°8184 (chd.lu, non voté). Les prix affichés ne sont pas des prix de vente. Les chiffres de ce rapport sont valables un trimestre — au-delà, demandez l’édition à jour.',
        statement: 'Un chiffre sourcé invite le lecteur à vérifier. C’est exactement pour ça qu’il faut le sourcer.',
        contact: 'Ayrton Silva · Luxembourg — pour l’édition à jour de ce rapport ou une analyse de votre situation : écrivez-moi.',
        disclaimer: 'Analyse générée à titre d’information uniquement — ce n’est pas un conseil en investissement, fiscal ou juridique. Toute transaction immobilière au Luxembourg requiert un notaire ; le traitement fiscal dépend de la situation personnelle et doit être confirmé auprès du notaire, de l’Administration des contributions directes, ou d’un conseiller fiscal.',
      },
    ],
  },
  en: {
    docLabel: 'The Southern Report · August 2026 edition',
    cover: {
      kicker: 'Property market · Southern belt',
      title: 'The Southern<br>Report.',
      sub: 'Six communes, verifiable figures, and what Luxembourg does not publish. Esch-sur-Alzette · Differdange · Dudelange · Bettembourg · Sanem · Pétange.',
      band: [
        ['6', 'communes analysed'],
        ['1,641', 'active listings counted'],
        ['50.8 : 1', 'Dudelange’s sale-to-rent ratio'],
        ['0', 'invented figures'],
      ],
      who: 'Ayrton Silva',
      what: 'Real estate agent · Luxembourg — sourced analysis, verifiable method',
      date: 'Reference data: July 2026 · gathered 10/08/2026 · valid for one quarter',
    },
    pages: [
      {
        rubric: 'Method',
        h2: 'What this report refuses to do',
        lede: 'Luxembourg publishes no transaction register, no days-on-market, no absorption rate. This report marks those as absent rather than estimating them.',
        body: 'The figures that follow rest on two kinds of source: asking prices (immotop.lu, athome.lu — what sellers want) and the Observatoire de l’Habitat’s aggregated notarial prices (what actually gets paid, published quarterly with a lag). The gap between the two is itself information: in Esch-sur-Alzette it is roughly €950/m².',
        table: {
          head: ['Metric expected by Anglo-Saxon models', 'Status in Luxembourg'],
          rows: [
            ['True median sale price', 'impossible — no public register'],
            ['Sale-to-list price ratio', 'impossible'],
            ['% sold above asking', 'impossible'],
            ['Average days on market', 'not published'],
            ['Months of inventory by commune', 'not published'],
            ['Rental vacancy rate', 'not published by commune'],
          ],
        },
        statement: 'An honest analyst tells you what they do not know. It is how you spot one.',
      },
      {
        rubric: 'Overview',
        h2: 'Six communes, three speeds',
        lede: 'The south is not one market. In July 2026, neighbouring communes are moving in opposite directions.',
        table: {
          head: ['Commune', 'Asking price', '1 year', 'Rent', 'Rent 1 yr', 'Sale/rent'],
          rows: [
            ['Esch-sur-Alzette', '€7,149/m²', '−1.31 %', '€28.17', '+3.22 %', '17.6 : 1'],
            ['Bettembourg', '€7,070/m²', ['−3.64 %', true], '€22.97', '+1.10 %', '22.3 : 1'],
            ['Sanem', '€6,773/m²', '−2.99 %', '€25.38', '+4.53 %', '46.2 : 1'],
            ['Dudelange', '€6,628/m²', '+0.52 %', '€25.76', ['+12.34 %', true], ['50.8 : 1', true]],
            ['Differdange (Niederkorn)', '€6,317/m²', '−0.91 %', '€28.27', '+7.53 %', '30 : 1'],
            ['Pétange', '€6,276/m²', '+0.18 %', '€25.85', '+8.61 %', '27.4 : 1'],
          ],
        },
        body: 'Bettembourg and Sanem are correcting from recent peaks (September and December 2025). Dudelange and Pétange have already corrected and are stabilising. Esch and Differdange are drifting gently. Three different phases of the cycle, fifteen kilometres apart.',
        note: 'Sources — immotop.lu communal series (July 2026) · Observatoire de l’Habitat (April 2026). Asking prices, not sale prices.',
      },
      {
        rubric: 'The dominant fact',
        h2: 'The rental shortage is a legal artefact',
        lede: 'Across the south, for-sale stock dwarfs rental stock. That is not demographics — it is the law.',
        bigfig: ['254 / 5', ''],
        body: 'Dudelange has 254 properties for sale against 5 to rent — the most extreme imbalance I have measured in Luxembourg. The statutory rent cap (5 % of revalued invested capital, law of 21/09/2006) compresses yield to the point where owners choose selling over letting. The mechanical result: where there is least to rent, rents rise fastest. Dudelange shows +12.34 % rent growth in one year.',
        table: {
          head: ['Commune', 'For sale', 'To rent', 'Ratio', 'Rent, 1 yr'],
          rows: [
            ['Dudelange', '254', '5', ['50.8 : 1', true], ['+12.34 %', true]],
            ['Sanem', '231', '5', '46.2 : 1', '+4.53 %'],
            ['Pétange', '274', '10', '27.4 : 1', '+8.61 %'],
            ['Bettembourg', '89', '4', '22.3 : 1', '+1.10 %'],
          ],
        },
        statement: 'Draft law no. 8184 would cut the cap from 5 % to 3.5 % on new leases. Not passed, not retroactive — and no serious rental decision should be made before its fate is known.',
      },
      {
        rubric: 'The lesson of scale',
        h2: 'The commune average is a statistical lie',
        lede: 'In the south of 2026, dispersion between localities of one commune exceeds dispersion between communes.',
        table: {
          head: ['Locality (commune)', '€/m²', '1 year'],
          rows: [
            ['Belvaux (Sanem)', '€6,926', ['+2.9 %', true]],
            ['Soleuvre (Sanem)', '€6,741', '−5.7 %'],
            ['Ehlerange (Sanem)', '€6,035', ['−11.0 %', true]],
            ['Fennange (Bettembourg)', '€7,714', ['−10.6 %', true]],
            ['Abweiler (Bettembourg)', '€7,187', '0.0 %'],
            ['Pétange locality', '€6,297', '+1.3 %'],
            ['Lamadelaine (Pétange)', '€6,054', '−5.2 %'],
          ],
        },
        body: 'Fourteen points of divergence in one year between Belvaux and Ehlerange — inside the same 25 km² commune. Belvaux touches the Belval campus; Ehlerange is furthest from it. In Bettembourg two localities lose more than 10 % while a third does not move. In Esch, gross yield runs from 2.29 % (Grenz) to 5.05 % (Al-Esch) depending on the neighbourhood.',
        statement: 'Any decision taken on a commune average is taken on a number that describes no real address.',
      },
      {
        rubric: 'The real cost',
        h2: 'A €545,000 property commits €588,600',
        lede: 'Acquisition costs are not a footnote. They are the basis of any serious calculation — and the property’s use changes everything.',
        table: {
          head: ['Item', 'Amount'],
          rows: [
            ['Property price', '€545,000'],
            ['Registration duty (6 %)', '€32,700'],
            ['Transcription duty (1 %)', '€5,450'],
            ['Notary (~1 %)', '€5,450'],
            ['Capital actually invested', ['€588,600', true]],
          ],
        },
        body: 'As a primary residence, the Bëllegen Akt erases up to €40,000 of duty per buyer (amount confirmed by the law of 03/07/2025; a 16/07/2026 release announces €45,000, not consolidated at the time of writing — confirm with the notary). Cash at signing then falls to around €5,450. On a rental the credit does not apply: budget roughly €152,600 in cash on the same property at 80 % LTV.',
        statement: 'Buying to live and buying to let is the same property and two operations with nothing in common. Thirty times more cash in the second case.',
      },
      {
        rubric: 'Your four checks',
        h2: 'Before any offer in the south',
        lede: 'None is spectacular. Together they prevent almost every unpleasant surprise I have seen land after signature.',
        checklist: [
          ['01 · The definitive energy certificate', 'Not the provisional one. Across the comparables captured in Esch, the gap between unrenovated and renovated stock reaches +38 % per m². The premium rests on a document — demand it.'],
          ['02 · The managing agent’s budget and reserve fund', 'A five-unit co-ownership splits a roof across five shares instead of thirty. The governance is simple; the invoice is not.'],
          ['03 · The parcel’s zoning', 'PAG, PAP, flood zones (the Alzette and the Chiers cross the basin), and CASIPO — the register of potentially polluted sites, unavoidable on a former steelworks basin. Fifteen minutes on geoportail.lu.'],
          ['04 · The tax amounts, with the notary', 'Bëllegen Akt, capital gains regime, deduction caps: three figures that moved recently. No simulation replaces a confirmation.'],
        ],
        statement: 'These are not investor precautions. They are the minimum for buying a home — and almost nobody does all four.',
      },
      {
        rubric: 'Sources and limits',
        h2: 'Check me',
        lede: 'Every figure in this report carries its source. What Luxembourg does not publish is not estimated — it is stated.',
        body: 'Prices and stock: immotop.lu communal series, reference period July 2026, gathered 10/08/2026. Notarial prices: Observatoire de l’Habitat (April 2026). Rail: cfl.lu and station records. Schools: lnbd.lu, lbv.lu, lma.lu. Legal framework: law of 21/09/2006 (rent cap), law of 03/07/2025 (Bëllegen Akt), draft law no. 8184 (chd.lu, not passed). Asking prices are not sale prices. The figures in this report are valid for one quarter — beyond that, ask for the current edition.',
        statement: 'A sourced number invites the reader to check. That is exactly why you source it.',
        contact: 'Ayrton Silva · Luxembourg — for the current edition of this report or an analysis of your situation: write to me.',
        disclaimer: 'Generated analysis for information purposes only — not investment, tax or legal advice. Every property transaction in Luxembourg requires a notary; tax treatment depends on personal circumstances and must be confirmed with the notary, the Administration des contributions directes, or a tax adviser.',
      },
    ],
  },
};
